### ISSUE TITLE
Missing `SID_IDENTIFIER_AUTHORITY` constants

### ISSUE THREAD

**Issue by Soul85** [microsoft/win32metadata#1337]
As an example, `SECURITY_NT_AUTHORITY`. Referred to in [Well-known SIDs](https://learn.microsoft.com/en-us/windows/win32/secauthz/well-known-sids) list.

**Comment by mikebattista** [comment]
@kennykerr / @riverar thoughts on this?

**Comment by kennykerr** [comment]
I really don't like these type-specific attributes, like the existing `PropertyKeyAttribute` attribute for `PROPERTYKEY` constants. It's just not generic at all. I'm not sure what the solution is but I'd rather not add more custom attributes if possible. Ideally, we can have some kind of generic and open-ended attribute that can express an initializer list for more than just one type.

**Comment by mikebattista** [comment]
@aarnott any thoughts on @kennykerr's recommendation? Are you handling the TD_WARNING_ICON scenario today?

**Comment by riverar** [comment]
I can't get CsWin32 to generate `TD_WARNING_ICON` but assuming it did, `TaskDialog` takes a `PWSTR` so probably not a great example of `TD_WARNING_ICON` coercion.

Nevertheless, sounds like a good idea to me. Will need some light docs on how to interpret the list items (e.g. 0,0xA vs 0,10, spaces, alternate ways to represent the list separator `,` as a list member, etc.)

**Comment by AArnott** [comment]
> I can't get CsWin32 to generate TD_WARNING_ICON

Really? What version are you using, @riverar? It came right up for me and generated this:

```cs
internal static readonly unsafe winmdroot.Foundation.PCWSTR TD_WARNING_ICON = (char*)(-1);
```

This is a simple case because this constant is typed as a typedef struct, so casting is generally sufficient to get it to work. 
`PROPERTYKEY` is significantly more complex because it has 2 fields. Initializing that with just a byte array would require that CsWin32 understand memory layout, the number of bytes in each type, etc. And if those fields were structs in their own right, it would get much worse. 
And considering that some structs have sizes and memory layouts that vary with pointer size, a byte array for a constant would seem to be unable to represent all the possibilities.
I'm therefore not bullish on the idea of a general attribute that can be used for all types of constants. 

`SID_IDENTIFIER_AUTHORITY` having only a `byte[]` seems easy enough to represent via an attribute, if we can't just naturally embed the byte data in metadata, which may be possible.

**Comment by kennykerr** [comment]
I'm not suggesting copying bits to initialize structs. I don't know of a language where that would work reliably, taking into account alignment and padding. I'm suggesting that when the literal value is a string and the constant type is a struct that the string represent a list of primitive values used to initialize the struct. So if the struct has field `int A` followed by field `int B`, the string might be "4,5". Tools would then need to parse this list of values and generate corresponding language-specific code to initialize the struct. 

The trouble with the `PropertyKeyAttribute` approach is that it is not scalable. It does not account for types we don't know about. A third party wants to represent their own types in metadata but cannot because they aren't known in advance by the winmd generator as well as every single language projection.

**Comment by AArnott** [comment]
Do all the constant structs have only primitive fields? Or do we have to account for structs within structs?

**Comment by kennykerr** [comment]
We should probably support something like `1, {2, 3}, 4` for structs with fields of structs.

**Comment by AArnott** [comment]
That should work.

**Comment by mikebattista** [comment]
> I'm not suggesting copying bits to initialize structs. I don't know of a language where that would work reliably, taking into account alignment and padding. I'm suggesting that when the literal value is a string and the constant type is a struct that the string represent a list of primitive values used to initialize the struct. So if the struct has field `int A` followed by field `int B`, the string might be "4,5". Tools would then need to parse this list of values and generate corresponding language-specific code to initialize the struct.

Given that we have to define this in C#, what would be the right way to define a constant whose type is a struct but whose value is a string? The obvious options don't compile.

**Comment by AArnott** [comment]
You can't do it in C# like that. You could use an attribute that takes a string parameter though.

**Comment by AArnott** [comment]
I'm hoping @kennykerr can offer an example, as I'm not familiar with this struct/constant.

**Comment by kennykerr** [comment]
An example of what?

**Comment by kennykerr** [comment]
> Given that we have to define this in C#, what would be the right way to define a constant whose type is a struct but whose value is a string? The obvious options don't compile.

Would an attribute not work? 

```C#
[Constant("1, {2, 3}, 4")]
public static SOME_STRUCT SOME_CONSTANT;
```

**Comment by riverar** [comment]
`SECURITY_NT_AUTHORITY` example:

Original:
```cpp
typedef struct _SID_IDENTIFIER_AUTHORITY {
  BYTE Value[6];
}
// ...
#define SECURITY_NT_AUTHORITY           {0,0,0,0,0,5}
```

Metadata:
```csharp
[Constant("{ 0, 0, 0, 0, 0, 5 }"]
public static ... SID_IDENTIFIER_AUTHORITY SECURITY_NT_AUTHORITY;
```

`PKEY_Address_Country` example:

Original:
```cpp
DEFINE_PROPERTYKEY(PKEY_Address_Country, 0xC07B4199, 0xE1DF, 0x4493, 0xB1, 0xE1, 0xDE, 0x59, 0x46, 0xFB, 0x58, 0xF8, 100);
```

Metadata:
```csharp
[Constant("{ { 0xC07B4199, 0xE1DF, 0x4493, 0xB1, 0xE1, 0xDE, 0x59, 0x46, 0xFB, 0x58, 0xF8 }, 100 }")]
public static ... PROPERTYKEY PKEY_Address_Country;
```

**Comment by mikebattista** [comment]
Sounds good. Thanks.

**Comment by mikebattista** [comment]
The build is still not recognizing this for some reason. I don't get any diffs even after a clean build.

I left off at https://github.com/microsoft/win32metadata/tree/mikebattista/structinitializers if someone wants to take a look.

**Comment by riverar** [comment]
@mikebattista Fixed.

**Comment by mikebattista** [comment]
Thanks!
