### ISSUE TITLE
ConstantWriter emits unchecked integers in unsigned integer enumerations

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#1369]
Example invalid generated output:
```csharp
public enum D3D12_BARRIER_SYNC : uint
{
    D3D12_BARRIER_SYNC_NONE = 0,
    D3D12_BARRIER_SYNC_ALL = 0x1,
    // ...
    D3D12_BARRIER_SYNC_SPLIT = unchecked((int)(0x80000000)),
}
```
```
error CS0031: Constant value '-2147483648' cannot be converted to a 'uint'
```

Seems to be hardcoded here:
https://github.com/microsoft/win32metadata/blob/6627267e04c6535b822e9ac89c735ca2b315c63f/sources/MetadataUtils/ConstantWriter.cs#L188-L191

Repro: TBD

**Comment by MarijnS95** [comment]
You can find a repro in https://github.com/microsoft/DirectX-Headers/pull/82 :grimacing:

**Comment by mikebattista** [comment]
I ran into this trying to fix https://github.com/microsoft/win32metadata/issues/1401 as well but haven't been able to track down where this is coming from.

@riverar, I don't believe the line you linked is the culprit. That is for constants that we scrape and turn into enums not enums that are scraped directly from the headers.

+@tannergooding @sotteson1 @chenss3 for additional eyes on this.

**Comment by tannergooding** [comment]
It's possible ClangSharp has some incorrect handling in `UncheckStmt` (https://source.clangsharp.dev/#ClangSharp.PInvokeGenerator/PInvokeGenerator.cs,5894), but I would typically expect that to "work correctly" since `GetTargetTypeName` explicitly looks for type remappings done to enums: https://source.clangsharp.dev/#ClangSharp.PInvokeGenerator/PInvokeGenerator.cs,2c230d2bbc5aba9c (this presumes some `--with-type D3D12_BARRIER_SYNC=uint`)

That being said, why is this typed as `uint` on the win32metadata side? I don't see anything in the header or idl that indicates `UINT` is the correct type here. In fact if you use something like godbolt to check, you'll see that `D3D12_BARRIER_SYNC_SPLIT` is considered negative, not positive: https://godbolt.org/z/jMd95TKe5 (the same repro's in a local MSVC using the official header).

The sign of types is important and there are platforms (such as RISC-V) where using the incorrect type will result in incorrect data. This may be impactful to future platforms that Windows could theoretically support.

**Comment by mikebattista** [comment]
+@damyanp

Are these enums supposed to be int? What does it mean for a flags enum to be int vs. uint? Is this D3D12_BARRIER_SYNC enum supposed to be used in places that require int or uint? The other flags enums that are scanned seem to be correctly identified as uint without issue.

If I add --with-type D3D12_BARRIER_SYNC=uint then below is what clangsharp produces. You can see it's natively scanning it as an int given the NativeTypeName attribute. Though with --with-type, there's no more unchecked issue for this enum, and the enum is typed as a uint.

```
[NativeTypeName("int")][global::System.Flags]    public enum D3D12_BARRIER_SYNC : uint
    {
        D3D12_BARRIER_SYNC_NONE = 0,
        D3D12_BARRIER_SYNC_ALL = 0x1,
        D3D12_BARRIER_SYNC_DRAW = 0x2,
        D3D12_BARRIER_SYNC_INPUT_ASSEMBLER = 0x4,
        D3D12_BARRIER_SYNC_VERTEX_SHADING = 0x8,
        D3D12_BARRIER_SYNC_PIXEL_SHADING = 0x10,
        D3D12_BARRIER_SYNC_DEPTH_STENCIL = 0x20,
        D3D12_BARRIER_SYNC_RENDER_TARGET = 0x40,
        D3D12_BARRIER_SYNC_COMPUTE_SHADING = 0x80,
        D3D12_BARRIER_SYNC_RAYTRACING = 0x100,
        D3D12_BARRIER_SYNC_COPY = 0x200,
        D3D12_BARRIER_SYNC_RESOLVE = 0x400,
        D3D12_BARRIER_SYNC_EXECUTE_INDIRECT = 0x800,
        D3D12_BARRIER_SYNC_PREDICATION = 0x800,
        D3D12_BARRIER_SYNC_ALL_SHADING = 0x1000,
        D3D12_BARRIER_SYNC_NON_PIXEL_SHADING = 0x2000,
        D3D12_BARRIER_SYNC_EMIT_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO = 0x4000,
        D3D12_BARRIER_SYNC_VIDEO_DECODE = 0x100000,
        D3D12_BARRIER_SYNC_VIDEO_PROCESS = 0x200000,
        D3D12_BARRIER_SYNC_VIDEO_ENCODE = 0x400000,
        D3D12_BARRIER_SYNC_BUILD_RAYTRACING_ACCELERATION_STRUCTURE = 0x800000,
        D3D12_BARRIER_SYNC_COPY_RAYTRACING_ACCELERATION_STRUCTURE = 0x1000000,
        D3D12_BARRIER_SYNC_SPLIT = 0x80000000,
    }
```

**Comment by tannergooding** [comment]
> What does it mean for a flags enum to be int vs. uint?

Not much in .NET since we don't have the same implicit conversions that C/C++ has.

That being said, the win32metadata repo is meant to be usable from many languages where such implicit conversions might exist. In such scenarios, comparisons such as `value > 0` will never be true for `uint` but would have been true for `int`. Since the type of the enum is `signed` in C/C++, this can lead to subtle differences in codegen between the platforms.

There are also some target platforms (such as RISC-V and I believe MIPS as well) where the sign of the type matters to the calling convention. On 64-bit platforms, a 32-bit value is sign or zero-extended to fill the register and so if typed as `uint` then `D3D12_BARRIER_SYNC_SPLIT` will be passed as `0x00000000_80000000` but as `int` (like in C/C++) it will be passed as `0xFFFFFFFF_80000000` and this can cause other downstream differences and bad behaviors.

In general we should aim to exactly match the signedness and other behaviors as exhibited by C/C++. Likewise, for cases like `char`, `long`, `unsigned long`, or `wchar_t` where the exact size and/or signedness can vary based on target platform/architecture, there should be enough information in the metadata to "recover" the original type so that languages can do the "correct" thing.

**Comment by mikebattista** [comment]
Also when I remove your previous workaround.

```
Windows.Win32.Graphics.Direct3D12.D3D12_BARRIER_ACCESS.value__...System.UInt32 => System.Int32
Windows.Win32.Graphics.Direct3D12.D3D12_BARRIER_SYNC.value__...System.UInt32 => System.Int32
winmd1: Windows.Win32.Graphics.Direct3D12.D3D12_BARRIER_ACCESS.D3D12_BARRIER_ACCESS_NO_ACCESS = 2147483648, winmd2 = -2147483648
winmd1: Windows.Win32.Graphics.Direct3D12.D3D12_BARRIER_SYNC.D3D12_BARRIER_SYNC_SPLIT = 2147483648, winmd2 = -2147483648
```
