### ISSUE TITLE
Is there corresponding function to `IEIsProtectedModeProcess`?

### ISSUE THREAD

**Issue by KisaragiEffective** [microsoft/win32metadata#1448]
Hello!
I am looking a function that corresponds [`IEIsProtectedModeProcess`](https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ms537316(v=vs.85)?redirectedfrom=MSDN), but it could not be found in `windows::Win32::Networking::WinInet`.

How can I use it from this awesome crate? Thank you :)

**Comment by mikebattista** [comment]
Looks like we need to specify the DllImport in libMappings.rsp for these.

**Comment by riverar** [comment]
@KisaragiEffective This should be available in the next `windows` crate release. Stay tuned!

**Comment by kennykerr** [comment]
@mikebattista I'm having a little trouble with this one. Did you mean for these APIs to be lumped into `Windows.Win32.Web.MsHtml`? That's a namespace that's so vast and generally useless that I exclude it entirely from windows-rs.

Can we move them to a dedicated namespace?

**Comment by kennykerr** [comment]
Also the entry point for `IEFindFirstFile` seems a little fishy.

```C#
[DllImport("Ieframe.dll", EntryPoint = "?IEFindFirstFile@@YGPAXPB_WPAU_WIN32_FIND_DATAA@@@Z", ExactSpelling = true, PreserveSig = false)]
public unsafe static extern HANDLE IEFindFirstFile([In][Const] PWSTR lpFileName, [In] WIN32_FIND_DATAA* lpFindFileData);
```

**Comment by mikebattista** [comment]
This header was already included at https://github.com/microsoft/win32metadata/blob/main/generation/WinSDK/Partitions/InternetExplorer/settings.rsp and we just fixed the lib mappings. What subset of those headers would you want to split off? I'm not sure I'd create a whole new namespace just for this header.

I'm not sure where the EntryPoints are coming from and why only some of the APIs have this. @tannergooding do you know where this might be coming from? The header being scanned is https://github.com/microsoft/win32metadata/blob/main/generation/WinSDK/RecompiledIdlHeaders/um/IEPMapi.h.

**Comment by tannergooding** [comment]
It's directly declared as the following, with no containing scope:
```cpp
HANDLE IEFindFirstFile(
  _In_ LPCWSTR lpFileName,
  _In_ LPWIN32_FIND_DATA lpFindFileData
);
```

Therefore its processed as a `C++` export. It needs to explicitly be marked as `extern "C"` and have the "correct" calling convention for it to be handled otherwise.

It's possible this is one of the headers that isn't meant to be included directly and that this is normally covered by some other header's `extern "C" { }`, etc

**Comment by kennykerr** [comment]
Many smaller namespaces are easy to manage - literally like including just that one "header" that you intend to use - but monolithic namespaces are very difficult to consume as they can't be subdivided. 

At the very least, the `MsHtml` namespace should *only* include the `mshtm*.h` headers. That would make excluding just MsHtml easier without impacting those other APIs that may be useful to some callers. MsHtml was only intended for JScript and VBScript clients.

**Comment by mikebattista** [comment]
@tannergooding We generally can't/don't change the original header files for compatibility reasons. Is there anything else we can do here aside from just not scraping this header?

@kennykerr I'd be ok leaving MsHtml headers in the MsHtml namespace and moving everything else to Windows.Win32.Web.InternetExplorer. Would that work?

**Comment by kennykerr** [comment]
Sure, that would be an improvement - thanks!

**Comment by tannergooding** [comment]
>We generally can't/don't change the original header files for compatibility reasons. Is there anything else we can do here aside from just not scraping this header? From a scan of the headers, I don't see these declared anywhere else.

You can explicitly tell ClangSharp the "correct" export name to use or process the header indirectly like TerraFX does.

------------

For the former, it's just passing in `--with-manual-import IEFindFirstFile=IEFindFirstFile`. The left hand side is the remapped name (that is the name of the function emitted in C#) and the right hand side is the export name (that is what you want as the `EntryPoint`). If these match, it will drop specifying the EntryPoint altogether since the default is to match names exactly.

------------

For the latter, you'd basically do what TerraFX.Interop.Windows does. An example of that is here: https://github.com/terrafx/terrafx.interop.windows/tree/main/generation/DirectX/um/d2d1

Essentially there is a local header `um-d2d1.h` which itself is:
```
#include "..\..\..\TerraFX.h"
#include <d2d1.h>
```

This is the file passed into ClangSharp to parse (`--file um-d2d1.h`). You then keep the traversal as originally intended (`--traverse C:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/um/d2d1.h`).

You can customize this local header with any extra defines/macros, required headers (e.g. `#include <Windows.h>` is common), that need to be included beforehand, or specializations like `extern "C" { #include <d2d1.h> }` if you need to tweak how things are parsed slightly without actually modifying the SDK sources.

**Comment by mikebattista** [comment]
The `extern "C"` approach worked. Thanks!
