### ISSUE TITLE
`GetCommandLine` should return a pointer to a constant string

### ISSUE THREAD

**Issue by ChrisDenton** [microsoft/win32metadata#1454]
According to [the docs](https://learn.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-getcommandlinew#remarks), the header type is wrong to use an `LPTSTR` when it should be a `LPCTSTR`:

> The lifetime of the returned value is managed by the system, applications **should not** free or **modify this value**.

**Comment by mikebattista** [comment]
@kennykerr / @riverar could you clarify what should change here? The data type? Add an attribute?

**Comment by kennykerr** [comment]
This is a little complicated because the metadata doesn't distinguish between `PCWSTR` and `PWSTR` and that happens to be a really important distinction for languages like C++ and Rust so Rust reconstructs the `PCWSTR` from the `PWSTR` based on context. In this case, it is not inferring that it should be const. If a `PWSTR` return type is always assumed to be const then we can update Rust to reflect that. Otherwise, we'll need a hint.

**Comment by kennykerr** [comment]
Here's an example in Rust. https://github.com/microsoft/windows-rs/compare/return_type_to_const?expand=1

The change is simple and while it fixes `GetCommandLine` it can potentially break other APIs where the return type is meant to be mutable.

**Comment by mikebattista** [comment]
Should we just add `return: [Const]`? We generally differentiate by applying `[Const]` as with https://github.com/microsoft/win32metadata/pull/1480.

**Comment by kennykerr** [comment]
Yes, if that adds the same `Const` attribute to the return parameter in metadata then that should work.

**Comment by kennykerr** [comment]
I see `[return: Const]` is already applied to various return parameters so that should work great.
