### ISSUE TITLE
Metadata attributes

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#1467]
All of the metadata attributes for the Windows Runtime are found in the `Windows.Foundation.Metadata` namespace. Since this metadata is the model for the Win32 metadata, can we move the Win32 metadata attributes into the `Windows.Win32.Foundation.Metadata` namespace rather than the existing `Windows.Win32.Interop`?

**Comment by mikebattista** [comment]
Looks like the binary name needs to change as well.

@sotteson1 can you clarify the reason these attributes are defined in a different DLL instead of in the main winmd?

Is changing the namespace here enough motivation to move these definitions into the main winmd, or do we still want to keep them separate?
