### ISSUE TITLE
`generation/WinSDK/manual/Backup.cs` could be removed

### ISSUE THREAD

**Issue by xtqqczze** [microsoft/win32metadata#1474]
dotnet/ClangSharp#366 is closed so it appears this file could be removed.

https://github.com/microsoft/win32metadata/blob/56ad3d0b8eacbb863ee95a4456a07f9cf79e792d/generation/WinSDK/manual/Backup.cs#L5-L7

**Comment by riverar** [comment]
Without this, metadata generates a struct that appears as such:

```csharp
public partial struct ACTIVATION_CONTEXT_COMPATIBILITY_INFORMATION
{
    [NativeTypeName("DWORD")]
    public uint ElementCount;

    [NativeTypeName("COMPATIBILITY_CONTEXT_ELEMENT[]")]
    public _Elements_e__FixedBuffer Elements;

    public partial struct _Elements_e__FixedBuffer
    {
        public COMPATIBILITY_CONTEXT_ELEMENT* e0;

        public unsafe ref COMPATIBILITY_CONTEXT_ELEMENT* this[int index]
        {
            get
            {
                fixed (COMPATIBILITY_CONTEXT_ELEMENT** pThis = &e0)
                {
                    return ref pThis[index];
                }
            }
        }
    }
}
```

This fails compilation with `error CS0214: Pointers and fixed size buffers may only be used in an unsafe context`. The linked issue shows a commit to 14.0.0-rc1 but doesn't seem to work for this case. Am testing with 15.0.0 now.

cc: @tannergooding

**Comment by riverar** [comment]
I pushed the scrape headers task to ClangSharp 15.0.2 and saw no difference.

**Comment by tannergooding** [comment]
@riverar could you share what options the codegen is being generated with?

TerraFX also uses ClangSharp and it is being generated correctly there: https://source.terrafx.dev/#TerraFX.Interop.Windows/Windows/um/winnt/ACTIVATION_CONTEXT_COMPATIBILITY_INFORMATION.cs,001635dc53802eb8 (actual source is here: https://github.com/terrafx/terrafx.interop.windows/blob/main/sources/Interop/Windows/Windows/um/winnt/ACTIVATION_CONTEXT_COMPATIBILITY_INFORMATION.cs)

There is also correspondingly a test covering this for the "Windows compatible codegen" that I believe microsoft/win32metadata is using: https://github.com/dotnet/ClangSharp/blob/main/tests/ClangSharp.PInvokeGenerator.UnitTests/CSharpCompatibleWindows/StructDeclarationTest.cs#L13-L32

It's notably covering primitive types, but at a glance I don't see any difference for other struct types.

**Comment by riverar** [comment]
@tannergooding Here's the base set of options

```
--additional
-Wno-expansion-to-defined
-Wno-ignored-attributes
-Wno-ignored-pragma-intrinsic
-Wno-nonportable-include-path
-Wno-pragma-pack
-Wno-comment
-Wno-extra-tokens
-Wno-unused-value
-Wno-#pragma-messages
-Wno-deprecated-declarations
-Wno-extern-c-compat
-Wno-extern-initializer
-D_USE_DECLSPECS_FOR_SAL=1
-D_PREFAST_=1
-DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP
-DMICROSOFT_WINDOWS_WINBASE_H_DEFINE_INTERLOCKED_CPLUSPLUS_OVERLOADS=0
-D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH=1
-DUCHAR_TYPE=wchar_t
--config
compatible-codegen
log-visited-files
log-exclusions
log-potential-typedef-remappings
exclude-funcs-with-body
generate-cpp-attributes
generate-native-inheritance-attribute
dont-use-using-statics-for-enums
exclude-anonymous-field-helpers
--methodClassName
Apis

```

**Comment by tannergooding** [comment]
Looks like a post-processing artifact of the `win32metadata` repo or maybe some other config knob or difference getting in the way...

I just tested with a `GenerateLocal.rsp`
```
--additional
-Wno-expansion-to-defined
-Wno-ignored-attributes
-Wno-ignored-pragma-intrinsic
-Wno-nonportable-include-path
-Wno-pragma-pack
-Wno-comment
-Wno-extra-tokens
-Wno-unused-value
-Wno-#pragma-messages
-Wno-deprecated-declarations
-Wno-extern-c-compat
-Wno-extern-initializer
-D_USE_DECLSPECS_FOR_SAL=1
-D_PREFAST_=1
-DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP
-DMICROSOFT_WINDOWS_WINBASE_H_DEFINE_INTERLOCKED_CPLUSPLUS_OVERLOADS=0
-D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH=1
-DUCHAR_TYPE=wchar_t
--config
compatible-codegen
log-visited-files
log-exclusions
log-potential-typedef-remappings
exclude-funcs-with-body
generate-cpp-attributes
generate-native-inheritance-attribute
dont-use-using-statics-for-enums
exclude-anonymous-field-helpers
--methodClassName
Apis
--namespace
Test
--include-directory
C:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/shared
C:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/um
C:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/winrt
--output
./gen/um/winnt.cs
--traverse
"C:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/um/winnt.h"
--file
"C:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/um/windows.h"
```

And the command line `ClangSharpPInvokeGenerator.exe @GenerateLocal.rsp`

That generates one file `winnt.cs` with the following definition on L13872:
```csharp
    public partial struct _ACTIVATION_CONTEXT_COMPATIBILITY_INFORMATION
    {
        [NativeTypeName("DWORD")]
        public uint ElementCount;

        [NativeTypeName("COMPATIBILITY_CONTEXT_ELEMENT[]")]
        public _Elements_e__FixedBuffer Elements;

        public partial struct _Elements_e__FixedBuffer
        {
            public _COMPATIBILITY_CONTEXT_ELEMENT e0;

            public unsafe ref _COMPATIBILITY_CONTEXT_ELEMENT this[int index]
            {
                get
                {
                    fixed (_COMPATIBILITY_CONTEXT_ELEMENT* pThis = &e0)
                    {
                        return ref pThis[index];
                    }
                }
            }
        }
    }
```

**Comment by tannergooding** [comment]
@riverar, yes. It also contains no unsafe code. Note that the two fields are `uint` and `_Elements_e__FixedBuffer`, which is a `struct`. The `unsafe` correctly exists on the `public unsafe ref _COMPATIBILITY_CONTEXT_ELEMENT this[int index]` which contains a `fixed` statement and thus requires it.

The `win32metadata` definition of `ACTIVATION_CONTEXT_COMPATIBILITY_INFORMATION` is incorrect, because it has the second field as a `COMPATIBILITY_CONTEXT_ELEMENT*`. It is not a pointer, but rather an inline buffer of type `COMPATIBILITY_CONTEXT_ELEMENT` with "length == 0".

This struct in general is not exactly representable in C#/.NET since we don't have a concept of "incomplete arrays" or "zero length" arrays. In C/C++, `sizeof(ACTIVATION_CONTEXT_COMPATIBILITY_INFORMATION)` is reported as `8` (`sizeof(uint)` + padding to account for "proper" alignment of `COMPATIBILITY_CONTEXT_ELEMENT`): [godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:32,endLineNumber:4,positionColumn:32,positionLineNumber:4,selectionStartColumn:32,selectionStartLineNumber:4,startColumn:32,startLineNumber:4),source:'%23include+%3CWindows.h%3E%0A%0Aint+getsizea()+%7B+return+sizeof(ACTIVATION_CONTEXT_COMPATIBILITY_INFORMATION)%3B+%7D%0Aint+getsizeb()+%7B+return+sizeof(COMPATIBILITY_CONTEXT_ELEMENT)%3B+%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:46.04228197718414,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:vcpp_v19_latest_x64,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-O2',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x64+msvc+v19.latest+(Editor+%231)',t:'0')),k:47.81313897630661,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x64+msvc+v19.latest',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x64+msvc+v19.latest+(Compiler+%231)',t:'0')),k:6.14457904650926,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

But when there is a non-zero amount of `Elements`, they appear inline and as trailing data which would not be possible with the `win32metadata` definition.

**Comment by riverar** [comment]
Ah I missed that inner `unsafe`, thanks! Will dig deeper, my snippet was output before any major transformation I believe.

**Comment by mikebattista** [comment]
I've got win32metadata generating the same definition now as @tannergooding. Is that what we want here?

**Comment by tannergooding** [comment]
> Is that what we want here?

Should be. ClangSharp was doing the right thing, ABI wise. Not aware of any actual bugs here.
