### ISSUE TITLE
Strange field names for `DEVMODE` inner unions: `Anonymous1`, `Anonymous2`

### ISSUE THREAD

**Issue by mikebattista** [microsoft/win32metadata#1481]

**Comment by mikebattista** [comment]
@kennykerr is this just how inner unions are named in the metadata? Or do we have a pattern for improving this?

**Comment by kennykerr** [comment]
These are unnamed nested unions so they don't really have names. The fact that winapi and Win32 metadata have different names for them is not surprising since you basically have to pick names arbitrarily. The Win32 metadata generator just has a simple process for generating unique names for nested unnamed types `AnonymousX`. So I wouldn't worry too much about this.

**Comment by mikebattista** [comment]
Ok. Thanks.
