### ISSUE TITLE
MessageBox function (winuser.h) constants are missing

### ISSUE THREAD

**Issue by wieslawsoltes** [microsoft/win32metadata#149]
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messagebox

e.g.: MB_OKCANCEL, MB_OK etc.

and are not generated when put in NativeMethods.txt

**Comment by zgabi** [comment]
I have the same problem with all constants... I could open a ticket for each, but I think it is a general problem...
For example I tried to use the follwing enums.values,
WindowLongIndexFlags.GWL_STYLE
(ComboBox)WindowStyles.CBS_DROPDOWNLIST
(Button)WindowStyles.BS_DEFPUSHBUTTON
WindowStyles.WS_CHILD and other WindowStyles contants
WindowsHookType.WH_CALLWNDPROCRET
WindowMessage.WM_GETFONT
EXECUTION_STATE.ES_DISPLAY_REQUIRED

That is 100% of my required constants, I did not found any.

**Comment by AArnott** [comment]
Constants should generate fine, including the two you named:
![53e22923-23ac-44d5-a935-4d5c363d0b82](https://user-images.githubusercontent.com/3548/105504553-1fde4c00-5c85-11eb-95a0-caf6ba879fd7.gif)

Now when a constant is included in an `enum`, the CsWin32 generator currently requires that you specify the enum type name rather than one of the enum value names. That is something we could improve on perhaps. Feel free to open an issue over at CsWin32 to discuss that.

Some of the enums @zgabi mentions are not (yet) enums in the metadata, so you would find the values as individual constants. #121 tracks many of these. Feel free to add more enum suggestions there.

#130 already tracks collecting the MB_ constants in an enum, so I'm closing this issue as there is nothing more wrong with the metadata for these that isn't already tracked.
