### ISSUE TITLE
Bug: ID3D11DeviceContext is marked Send and Sync

### ISSUE THREAD

**Issue by Muon** [microsoft/win32metadata#1516]
### Which crate is this about?

windows

### Crate version

0.47.0

### Summary

According to the [documentation](https://learn.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-render-multi-thread-intro), `ID3D11DeviceContext` is not thread-safe. However, it is marked Send and Sync here. Actually, it seems that many, if not most COM APIs are marked Send and Sync.

This should not be the case, since it opens up a potential double-free situation:
```rust
let x: IUnknown = f();
std::thread::scope(|s| {
    s.spawn(|| { let y = x.clone(); });
    s.spawn(|| { let z = x.clone(); });
});
```
If the `AddRef()` implementation is not atomic, you could end up with a double free due to a data race on the reference count causing it to be ultimately stored as 2 and not 3, even though `Release()` will be called 3 times.

**Comment by riverar** [comment]
@damyanp Is there any change needed here?

**Comment by damyanp** [comment]
Note that the D3D APIs are not COM APIs: they implement IUnknown, but don't take part in any of the rest of COM's machinery (apartments, marshaling etc.).  We call that NanoCOM.  I'm not aware of any NanoCOM Win32 APIs that don't have thread-safe AddRef/Release implementations.

For D3D12, we recognize that the general thread-safety model is not something that Rust's type system can understand, since in D3D12 we need to contend with the GPU timeline and applications need to be aware of this when managing GPU resources.

In D3D11, things are a bit different since much of the resource management is done below the API (ie in the runtime or the driver) which means that the API surface is more amenable to Rust's type system, and so at first glance it seems that maybe we should annotate ID3D11DeviceContext as non-thread-safe.  However, this is actually controllable at runtime - by default the individual methods are thread-safe.  If an application wanted to create a non-deterministic render by having multiple threads call DrawIndexed on the same device context without any locking between them then they can go ahead and do that.  If the D3D11 device was created with D3D11_CREATE_DEVICE_SINGLETHREADED then they'd risk corrupting internal data structures.

So I think in order to expose these APIs at the lowest level, without building in any additional policy, marking them as sync/send is appropriate.

**Comment by riverar** [comment]
Thanks @damyanp. Looks like there's no change needed here so will close this for now. @Muon Feel free to keep the discussion going if needed.
