### ISSUE TITLE
Attribute for base infrastructure than can be ignored

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/win32metadata#1563]
I want to provide a high-level projection where foundational stuff should be hidden from the user. For example, HSTRING and BSTR functions should be replaced with class wrappers and error-handling parts like GetLastError should be hidden in favour of the projection translating to/from exceptions.

**Comment by riverar** [comment]
I think we keep most of that in `Windows.Win32.Foundation`. Projection authors can handle those as they see fit. Did you have something specific in mind? (GetLastError is exported by kernel32 so is not a candidate.)

**Comment by mikebattista** [comment]
I believe you have what you need and can ignore or unwrap whatever metadata you don't want. See https://github.com/microsoft/win32metadata/blob/main/docs/projections.md#implementing-language-projections.

Since you mentioned `HSTRING` and `BSTR` which are both native typedefs, in particular read the section on `NativeTypedef` and `MetadataTypedef`.
