### ISSUE TITLE
ChangeServiceConfig dwServiceType not using ENUM_SERVICE_TYPE

### ISSUE THREAD

**Issue by Nuklon** [microsoft/win32metadata#1629]
https://learn.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-changeserviceconfigw

**Comment by mikebattista** [comment]
Several of these potential enum parameters also accept `SERVICE_NO_CHANGE` if you're not changing that parameter. That value is not part of these enums since we historically haven't duplicated shared values across enums as that causes problems with some projections.

@kennykerr @riverar @AArnott, if we assign enums here, will the developer experience for passing in `SERVICE_NO_CHANGE` be acceptable? Would you just need to cast it to the enum type when passing it in?

**Comment by kennykerr** [comment]
I'm slowly trying to get rid of the invented enums. 🫠

**Comment by mikebattista** [comment]
To be clear, the Rust projection is the main reason we've enforced this policy. If duplicating values across enums no longer bothers you, I'm happy to change course.

**Comment by kennykerr** [comment]
Duplicating them would certainly make it worse, if that's what you're asking. Rust aims to avoid the extra casting required for enums by treating them like the C-style constants they are, so duplicating them across enums would cause duplicate name collisions in the source.

**Comment by riverar** [comment]
I think ideally we'd have something like:

```csharp
public unsafe static extern BOOL ChangeServiceConfigW(
  ...
  [In] [AcceptsValuesFromEnumeration("Foo")] uint dwServiceType,
  ...
);
```

The `AcceptsValuesFromEnumeration` is opt-in. Then after unpacking the existing `ENUM_SERVICE_TYPE`, everything just works together.

```rust
ChangeServiceConfigW(..., SERVICE_KERNEL_DRIVER, ...);
ChangeServiceConfigW(..., SERVICE_NO_CHANGE, ...);
```

**Comment by mikebattista** [comment]
We have `[AssociatedEnum]`. We use that when the enum is one type and can be used in a parameter that is of another type.

**Comment by Nuklon** [comment]
An alternative would be to generate two methods, one with uint so you can pass whatever you choose, and one with the existing ENUM_SERVICE_TYPE.

**Comment by riverar** [comment]
> An alternative would be to generate two methods, one with uint so you can pass whatever you choose, and one with the existing ENUM_SERVICE_TYPE.

We have an open discussion on overloaded methods you might find interesting https://github.com/microsoft/win32metadata/issues/124

**Comment by mikebattista** [comment]
I don't think I would apply overloads here. If we still don't want to add the shared value to multiple enums, then either we apply the enum and you cast the shared value or we remove the enums entirely.

**Comment by AArnott** [comment]
The cast in C# would work, but it would be harder to discover. An enum strongly suggests to a C# programmer that the values in it are all-inclusive. And since the `SERVICE_NO_CHANGE` constant wouldn't be in the enum, CsWin32 wouldn't even generate it by default so the user would have to realize it was an option, add it to NativeMethods.txt, then use it with a cast. Not the end of the world, but I'd love to do better.

What if we allow multiple `[AssociatedEnum]` attributes on the same parameter? That would help in the CreateFile case as well, where some parameters take inputs from multiple enums. In the `ChangeServiceConfig` case, we could keep the standard enum, but also define another (one member) enum with `SERVICE_NO_CHANGE` on it. Then type the parameter as `uint` (or whatever) and attribute the parameter twice. Then CsWin32 or other projections could do any of a few things:
1. ignore the attributes and just use `uint`
2. Generate both enums automatically (or the values within the enums at least), and add API docs to the generated code encouraging the user to consider the content of both as available.
3. Generate a union enum and type the parameter as that so that everything is offered intuitively. (problem with this is interop with other APIs that use one of the individual enum types will still need a cast.) 

Wild idea: Maybe in C# we switch from enums to a typedef-esque struct with static members for each enum value. That would allow us to define implicit cast operators between the original struct/enum types and their unions.

**Comment by mikebattista** [comment]
I'm open to it.

Another potential option for a shared value like this is if we added a new attribute to the enum itself to indicate an additional shared constant:

```
[Flags]
[AssociatedConstant("SERVICE_NO_CHANGE")]
public enum ENUM_SERVICE_TYPE : uint
{
	SERVICE_DRIVER = 0xBu,
	SERVICE_KERNEL_DRIVER = 1u,
	SERVICE_WIN32 = 0x30u,
	SERVICE_WIN32_SHARE_PROCESS = 0x20u,
	SERVICE_ADAPTER = 4u,
	SERVICE_FILE_SYSTEM_DRIVER = 2u,
	SERVICE_RECOGNIZER_DRIVER = 8u,
	SERVICE_WIN32_OWN_PROCESS = 0x10u,
	SERVICE_USER_OWN_PROCESS = 0x50u,
	SERVICE_USER_SHARE_PROCESS = 0x60u
}
```

We could apply this attribute to multiple enums where the associated constant is shared without duplicating the definition. Projections can ignore it and the enum safely as before and we avoid any issues with duplicate definitions, or they could merge that constant into the enum definition.

This doesn't help when you have two distinct enums that could be used in the same parameter like CreateFile, but it could help the shared constant scenario. For CreateFile, your AssociatedEnum approach could help.

**Comment by AArnott** [comment]
Yes, your idea is a simpler and more elegant solution to this issue. I like it.

**Comment by riverar** [comment]
Does it make more sense to just use inheritance? Downside for Rust is the additional steps needed to get to the base type to unpack these enums.

```csharp
[Flags]
public enum SERVICE_CONFIG_COMMON_CONSTANTS
{
	SERVICE_NO_CHANGE = 4294967295UL,
}

[Flags]
public enum ENUM_SERVICE_TYPE : SERVICE_CONFIG_COMMON_CONSTANTS
{
	SERVICE_DRIVER = 0xBu,
	SERVICE_KERNEL_DRIVER = 1u,
	SERVICE_WIN32 = 0x30u,
	SERVICE_WIN32_SHARE_PROCESS = 0x20u,
	SERVICE_ADAPTER = 4u,
	SERVICE_FILE_SYSTEM_DRIVER = 2u,
	SERVICE_RECOGNIZER_DRIVER = 8u,
	SERVICE_WIN32_OWN_PROCESS = 0x10u,
	SERVICE_USER_OWN_PROCESS = 0x50u,
	SERVICE_USER_SHARE_PROCESS = 0x60u
}
```

**Comment by AArnott** [comment]
That isn't legal on the CLR. Enums are value-types and cannot derive from one another.

**Comment by riverar** [comment]
We don't care about CLR (a implementation of CLI) compatibility. But you're right, CLI constrains us here, darn! I'm still brainstorming here; the associated constant attribute on a enum feels a bit hokey.
