### ISSUE TITLE
Add `Task_DIALOG_NOTIFICATION` enum for `TDN_` constants and use in `PFTASKDIALOGCALLBACK` `msg` parameter

### ISSUE THREAD

**Issue by elachlan** [microsoft/win32metadata#1733]
https://learn.microsoft.com/en-us/windows/win32/controls/bumper-task-dialogs-reference-notifications
https://learn.microsoft.com/en-us/windows/win32/api/commctrl/nc-commctrl-pftaskdialogcallback

**Comment by elachlan** [comment]
@mikebattista Are we avoiding grouping the notification constants?

We previously did it in: https://github.com/microsoft/win32metadata/pull/1322

But it looks like that was undone?

**Comment by elachlan** [comment]
#810 removed it and I remember having conversations about "notification message constants" staying as constants because messages can contain values that aren't in the constant values.

Am I on the right track there?

**Comment by riverar** [comment]
Looking.

**Comment by riverar** [comment]
```csharp
// Windows.Win32.winmd, Version=56.0.13.25053, Culture=neutral, PublicKeyToken=null

public enum TASKDIALOG_NOTIFICATIONS
{
	TDN_CREATED,
	TDN_NAVIGATED,
	TDN_BUTTON_CLICKED,
	TDN_HYPERLINK_CLICKED,
	TDN_TIMER,
	TDN_DESTROYED,
	TDN_RADIO_BUTTON_CLICKED,
	TDN_DIALOG_CONSTRUCTED,
	TDN_VERIFICATION_CLICKED,
	TDN_HELP,
	TDN_EXPANDO_BUTTON_CLICKED
}

[StructLayout(LayoutKind.Auto, CharSet = CharSet.Auto)]
[UnmanagedFunctionPointer(CallingConvention.Winapi)]
public delegate HRESULT PFTASKDIALOGCALLBACK([In] HWND hwnd, [In] uint msg, [In] WPARAM wParam, [In] LPARAM lParam, [In] IntPtr lpRefData);
```

Looks like everything is here. What's missing @elachlan?

**Comment by elachlan** [comment]
I think we wanted to change PFTASKDIALOGCALLBACK to use the enum for the msg parameter. I believe last time we talked about msg parameters or fields we avoid limiting to the enums?

**Comment by riverar** [comment]
I think the problem here is that the enumeration in `commctrl.h` looks like this:

```cpp
typedef enum _TASKDIALOG_NOTIFICATIONS
{
   TDN_CREATED = 0,
   TDN_NAVIGATED = 1
   ...
}
```

The underlying type of this enumeration (`std::underlying_type<_TASKDIALOG_NOTIFICATIONS>::type`) via MSVC is `int`. But the callback `msg` parameter is defined as an `unsigned int`.

```cpp
typedef HRESULT (CALLBACK *PFTASKDIALOGCALLBACK)(_In_ HWND hwnd, _In_ UINT msg, _In_ WPARAM wParam,
  _In_ LPARAM lParam, _In_ LONG_PTR lpRefData);
```

So I don't think it's possible for us to make that association. (There's a long discussion about preserving ABI compatibility in https://github.com/microsoft/win32metadata/issues/1502.)

I think as a workaround in C#, you'll need to employ casting.

@mikebattista Does this sound right or did I miss something?

**Comment by elachlan** [comment]
I thought `[AssociatedEnum]` might be the answer here. Excellent!
