### ISSUE TITLE
Java Support

### ISSUE THREAD

**Issue by cbruegg** [microsoft/win32metadata#174]
It would be awesome to have autogenerated wrappers for Java, eliminating the need for incomplete third-party wrappers.

**Comment by fornever847** [comment]
Where can I do that at?

**Comment by AArnott** [comment]
This repo contains no language projections at all, but offers the metadata so that such can exist in other repos. I have heard of no plans for MS to create such a projection but we encourage all the various communities to create them or help maintain them where they exist, and work to make that much easier by consuming the metadata produced by this repo.

I think adding a Java projection would be great. But it is outside the scope of this repo.

**Comment by cbruegg** [comment]
@AArnott @kennykerr I'm a bit confused. The [announcement](https://blogs.windows.com/windowsdeveloper/2021/01/21/making-win32-apis-more-accessible-to-more-languages/) mentions:

> We will work with the community to support other languages based on [demand](https://github.com/microsoft/win32metadata/issues), partnering with existing community projects where appropriate.

Is there a better to place to show demand for other languages? Is the link wrong? Or did I misunderstand this?

**Comment by AArnott** [comment]
@cbruegg We won't *start* most of these language projections, but we will work with communities that build them. So creating an issue *here* doesn't seem the most appropriate place. I recommend you build up interest in the Java (or other) language community and start the project, then come back here and file issues or questions that you run into.

**Comment by mikebattista** [comment]
It is ok to start the discussion here by filing an issue. Though as others have pointed out, to scale we need the respective communities to build their own projections on top of the metadata that we produce, so generating interest and demand in those communities directly may help with getting traction. We'd love to see projections for all the languages that have been requested.

**Comment by mikebattista** [comment]
#183 captures the guidance for new language projection requests.
