### ISSUE TITLE
Python language projections

### ISSUE THREAD

**Issue by leonardder** [microsoft/win32metadata#182]
Hereby I'd like to suggest the creation of Python language projections for the Win32 API. I'm one of the developers of the [NVDA screen reader](https://nvaccess.org) that is written in Python for the most part and heavily relies on talking to the Win32 API. Currently this is performed using ctypes.

**Comment by kennykerr** [comment]
See https://github.com/microsoft/win32metadata/issues/174#issuecomment-766284319

**Comment by mikebattista** [comment]
#183 captures the guidance for new language projection requests.

**Comment by mikebattista** [comment]
@zooba and I met to brainstorm what an ideal Python projection would look like based on learnings from projects like pywin32 and ctypes. Below are the notes from that discussion for review and comment.

* Provide maximum API coverage for Win32 and COM
* APIs should be exposed as friendly Python interfaces rather than like ctypes
* Achieve seamless acquisition and “pay for play” by providing granular PIP packages under the [windows ](https://pypi.org/project/windows/) root
  * These packages would probably align with the namespaces we’ve added in the Win32 metadata
  * Ideally, the tooling used to build these packages could be used by developers directly to produce their own packages for just the APIs they need, if the Win32 namespaces aren’t granular enough
* These packages sim-ship with Python updates so they are available at launch

Let us know your thoughts and comments.
