### ISSUE TITLE
`IMMDevice::GetState`: Wrong function signature/return type

### ISSUE THREAD

**Issue by seritools** [microsoft/win32metadata#1856]
### Summary

https://learn.microsoft.com/en-us/windows/win32/api/mmdeviceapi/nf-mmdeviceapi-immdevice-getstate

In 0.52, this used to be `pub unsafe fn GetState(&self) -> Result<u32>`, as the underlying API returns a `HRESULT`, and passes the device state value through the out parameter if successful.

In 0.53 it's `pub unsafe fn GetState(&self, pdwstate: *mut u32) -> DEVICE_STATE`, somehow both returning `DEVICE_STATE` _and_ taking it as out parameter. Any indication that this is a fallible function is gone. I assume there  is some type confusion between `HRESULT` (= `u32`) and the newly-introduced `DEVICE_STATE` (= `u32`) type, causing this.

I think the correct signature would be `pub unsafe fn GetState(&self) -> Result<DEVICE_STATE>` to recover the original meaning and correct typing of this function.

### Crate manifest

```TOML
windows = { version = "0.53.0", features = "Win32_Media_Audio" }
```

**Comment by HEnquist** [comment]
I just looked at this function in windows 0.56, and I still see the same strange signature as in 0.53:
```
pub unsafe fn GetState(&self, pdwstate: *mut u32) -> DEVICE_STATE {
```
It does not look as if this was solved by the metadata update.

**Comment by riverar** [comment]
We haven't ingested new metadata on the Rust side that would have this fix yet. https://github.com/microsoft/windows-rs/tree/master/crates/libs/bindgen/default

Looks like this was fixed in https://github.com/microsoft/win32metadata/commit/f56f285dd44d5c2147f853bd1c22e1caa4a9d05a (March 4) and the last metadata release was https://github.com/microsoft/win32metadata/releases/tag/v59.0.13-preview (Feb 16).
