### ISSUE TITLE
Missing D3DX functions

### ISSUE THREAD

**Issue by chyyran** [microsoft/win32metadata#1867]
https://learn.microsoft.com/en-us/windows/win32/direct3d9/dx9-graphics-reference-d3dx

While D3DX is deprecated, it is still included as part of the Windows SDK and for legacy compatibility reasons I would like to use it in windows-rs.

**Comment by riverar** [comment]
These appear to be utility functions provided by `d3dx9.lib` and not Win32 or OS APIs. Don't think there's anything we can add to metadata here.

@damyanp Do the newer SDKs offer some backwards compatibility here?

**Comment by damyanp** [comment]
@jenatali or @walbourn, do you know much about `d3dx9.lib`?

**Comment by jenatali** [comment]
> it is still included as part of the Windows SDK

It is not. Chuck's the right contact here. Relevant: https://walbourn.github.io/legacy-d3dx-on-nuget/

**Comment by walbourn** [comment]
Direct3D 9, D3DX9, D3DX10, D3DX11 are all deprecated and legacy. D3DX9, D3DX10, D3DX11 hasn't been updated since June 2010, contains numerous bugs and known security issues, and is closed source that cannot be serviced. We released a NuGet with the SHA-256 resigned version of the original bits just to help unblock customers with older code bases, but we would absolutely not recommend using it for new projects.

https://walbourn.github.io/living-without-d3dx/

There is a Rust project already for DirectXTex: https://crates.io/crates/directxtex

I recommend using Direct3D 11 or Direct3D 12, and not using Direct3D 9 at all.
