### ISSUE TITLE
Missing COM interface for ISampleGrabber 

### ISSUE THREAD

**Issue by plafosse** [microsoft/win32metadata#1965]
Missing com interface for  [ISampleGrabber](https://learn.microsoft.com/en-us/windows/win32/directshow/isamplegrabber)

**Comment by mikebattista** [comment]
Per the docs, this is deprecated with strong recommendations to migrate forward, not in any Windows SDK since Vista, and not compatible with D3D headers later than version 7.

**Comment by mon** [comment]
This is a surprising response, because the metadata also exposes many other deprecated interfaces from DirectShow such as `IGraphBuilder`, `IMediaControl`, `IBaseFilter`, and `ICaptureGraphBuilder2`.

The top level README for win32metadata states it aims to "Provide the broadest API coverage possible", this seems to conflict with that goal. I hate the be that pain-in-the-ass user using (in my case, reverse-engineering) decades old APIs, but can the docs at least be adjusted to state that this project won't target deprecated APIs? Because I've always seen this project as "every winapi function in machine readable format", and this goes against that.

**Comment by plafosse** [comment]
How do you plan on handling future deprecations? Are these going to be actively removed? Seems like a more thoughtful approach would be to keep them around but have them marked as deprecated with some information regarding the time/version of deprecation
