### ISSUE TITLE
The CLSCTX enum is missing CLSCTX_ALL 

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#203]
Note this is a specific set of flags (not necessarily all of them). 😉

**Comment by sotteson1** [comment]
Hmm, this is a #define in combaseapi.h instead of a value on the enum. I could implement this as a constant, but it probably does belong on the enum. I don't yet have a way to inject enum values that aren't scraped from an original enum definition, so I'll need to add a way to do this, or I can exclude this one from being scraped and define the whole thing manually.
