### ISSUE TITLE
`ushort` where `char` ought to be

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#285]
As recently as at least `preview.22`, we have sightings of `ushort[]` where `char[]` are expected:

- [ ] `NOTIFYICONDATAW` fields

Similarly, I see `sbyte[]` where `byte[]` ought to be:

- [ ] `NOTIFYICONDATAA` fields

This, in spite of #59 already being "fixed".

**Comment by sotteson1** [comment]
When I resolved #59 as being fixed I was thinking of our change to make LPCWSTR/LPWSTR/LPSTR etc. to the native typedefs. I'll need to do something else for these fixed size char arrays.

**Comment by tannergooding** [comment]
I've explained this elsewhere but I made ClangSharp generate `ushort` rather than `char` for a few reasons:
* .NET `char` is not always blittable and defaults to `ASCII` (not UTF-16 nor UTF-8) on Windows. This means all instances of `char`, `ref char`, `in char`, `out char`, `char[]`, and `string` need an additional attribute such as `[MarshalAs(UnmanagedType.U2)]` or `CharSet.Unicode`. This is not necessary for `char*` or when `ushort` is used, thus reducing metadata bloat
* C `char` already has to be handled for the various `A` overloads of methods (as ASCII or even potentially as UTF-8 on newer versions of Windows: https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/use-utf8-code-page). These can only be represented by `byte` or `sbyte` plus the relevant SAL annotations and so a source generator already needs to to recognize and support these patterns. To that extent, needing to support `ushort` to `char` conversions isn't that much more, particularly when `C# `allows an implicit conversion in many cases (i.e. `ushort s = 'a';` is valid C#)
* C `wchar_t` is 2-bytes on Windows but 4-bytes on Unix, which can lead to incompatibilities when ClangSharp needs to generate bindings for non-windows platforms. Using `ushort` and `uint` explicitly helps avoid this problem.
* It is possible that some future variant of .NET (particularly one that targets web or cloud scenarios) decides that `char` should be 1-byte, not 2. Using `ushort` ensures that P/Invokes are compatible with such an environment. https://github.com/dotnet/corefxlab/issues/2350#issuecomment-742008691 is where this proposal was initially raised, including discussing ecosystem drawbacks, etc.

**Comment by AArnott** [comment]
> .NET char is not always blittable and defaults to ASCII (not UTF-16 nor UTF-8) on Windows 

Those are all .NET runtime concerns. The metadata describes the win32 API for more than just .NET. IMO we should use the most semantically rich types available in the metadata, and leave it to the projections to make runtime/language specific changes such as ensuring structs should be blittable. `char` is a UTF-16 type and therefore is more precise than `ushort` which conveys the idea of a number instead of a character.

> ASCII or... UTF-8... can only be represented by byte 

True. So an attribute is necessary there. I don't see that as a reason to *not* use `char` for UTF-16 though.

> C wchar_t is 2-bytes on Windows but 4-bytes on Unix, which can lead to incompatibilities when ClangSharp needs to generate bindings for non-windows platforms. Using ushort and uint explicitly helps avoid this problem.

I don't see what ClangSharp's xplat requirements have to do with how we may want to express Win32-specific metadata. 
What problem does using `ushort` instead of `char` solve for win32metadata, if any?

> It is possible that some future variant of .NET

IMO we shouldn't let a possible future disrupt us going along with a decade of precedent. And if that were to ever happen on .NET, that doesn't need to have any bearing on this metadata. If it ever happens, it is again a .NET-specific concern that CsWin32 will have to deal with, in those specific projects that make the (insanely disruptive) decision to redefine a primitive's native size.

**Comment by tannergooding** [comment]
> The metadata describes the win32 API for more than just .NET

Right, and so representing it a way that most closely matches the underlying ABI is goodness IMO. `wchar_t` is a either a keyword (C++) or a typedef (C) that maps to an actual underlying type such as `unsigned short` or `unsigned int` and is only required to be at least equivalent to `sbyte` or `byte` in C#. It is not strictly UTF16 data and not strictly 16-bits in length. Just like `char` in C/C++ is not strictly ASCII or UTF8 or even character data at all. Instead, these types merely represent the backing data point for certain types of string literals in the language (now `char16_t` and `char32_t` on the other hand are a different story).

> I don't see what ClangSharp's xplat requirements have to do with how we may want to express Win32-specific metadata.

ClangSharp is currently the backing generator for win32metadata. 

> What problem does using ushort instead of char solve for win32metadata, if any?

It correctly annotates that the Windows API expects 16-bit data and is both forward and backward compatible across any interpretation of the metadata format. 

It leaves no ambiguities of how the data is interpreted and defers to the SAL attributes to indicate whether it is a string, an array, or something else (which is already a requirement for every other string-like or character-like type).

This is simple and allows the logic to work regardless of whether the API takes `byte`, `sbyte`, `char`, `short`, `ushort`, `int`, `uint`, some theoretical new `CWChar` (to match the new `CLong` and `CULong` types we are exposing in .NET 6). In all cases, you pass the string into an API which does any encoding conversions required (and which may `nop`), and whose output is pinned. You then insert a cast from the encoding output to the input type required by the API.

> IMO we shouldn't let a possible future disrupt us going along with a decade of precedent.

I disagree, strongly. There has already been a lot of discussion around how to best handle UTF8 string types in .NET and one of the strongest proposals is to change how `char` and `string` are internally backed. Going with `ushort` adds near zero burden on the consumer of a raw API (for character literals or locals, there is currently an implicit conversion and for strings they insert a single cast from `char*` to `ushort*`). While the friendly API that takes `Span<char>`, `string`, and friends sees no functional difference because everything is handled internally by the source generator. The source generator itself should also see near zero change because it already has to handle similar scenarios for every other character-like and string-like type.
