### ISSUE TITLE
TRUE and FALSE

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#301]
Should the `TRUE` and `FALSE` constants be of type `Windows.Win32.SystemServices.BOOL`? Currently they're `int`.

**Comment by AArnott** [comment]
Should BOOL be an enum with two values? 😱

**Comment by weltkante** [comment]
> Should BOOL be an enum with two values?

There are APIs that return more than two values (most prominently [GetMessage](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmessage#return-value)), in case thats relevant to the decision

**Comment by weltkante** [comment]
The quote from the doc actually made me remember that often `BOOL` is documented as zero vs. nonzero not `TRUE` vs. `FALSE` - the constants are for generating `BOOL` values, not for comparing them. So making this an enum will probably lead to weird edge cases where people try to compare a `BOOL` with `TRUE` and its false yet still nonzero.

I don't know how clean the Windows API is in regard to nonzero `BOOL` values, aside from officially documented cases like GetMessage. Since all C/C++ code I've ever written or maintained never compared to `TRUE` literally I never ran into these cases if they exist, code always did the implicit nonzero check.

Making this an enum would be taking a leap of faith since APIs are usually not documented as returning `TRUE`, but rather nonzero (even if in practice that nonzero probably will be mostly `TRUE` anyways, but who knows for sure)

**Comment by AArnott** [comment]
Agreed. Let's not define an enum. I was mostly kidding on that anyway. But I learned some important things from your comments here, so thank you.
