### ISSUE TITLE
Reserved parameters/fields

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#323]
If there's a pointer-sized reserved parameter or field, it's much more convenient in Rust - perhaps in other languages as well - if that is an `IntPtr` type rather than a `void*` because a simple `0` will suffice. This is because Rust purposefully doesn't make it easy to use pointers. `CoInitializeEx`'s first parameter is a good example. It's very common to pass `0` as the first parameter in C++, but in Rust I need to use something far more wordy to achieve the same effect.

**Comment by AArnott** [comment]
For C# it's the opposite: `void*` can be set to `null` whereas `IntPtr` has to be `IntPtr.Zero` (or `default`).
I'd prefer we keep the type as it is defined in the headers. 

But if we know a field or parameter is "reserved" somehow, attributing it so projections can do something special seems great.

**Comment by weltkante** [comment]
"reserved" can mean a lot of things, so its dangerous to assume a specific meaning
- it previously had a documented meaning but since then has been decomissioned and is no longer used
- it is undocumented but used by some components (and may even be documented by those components!) - if you are an intended consumer you may want to actually make use of it
- its actually reserved for future extensions

unless you know the history and/or implementation details of what "reserved" means for a particular name you can't just rely on the documentation or name to disable usage of it

Examples:
- [`WM_PAINT`](https://docs.microsoft.com/en-us/windows/win32/gdi/wm-paint#remarks)
  > For some common controls, the default WM_PAINT message processing checks the wParam parameter. If wParam is non-NULL, the control assumes that the value is an HDC and paints using that device context.
- ['DllMain'](https://docs.microsoft.com/en-us/windows/win32/dlls/dllmain#parameters)
  > The lpReserved parameter indicates whether the DLL is being unloaded as a result of a FreeLibrary call, a failure to load, or process termination.

I know these are not strictly relevant to win32metadata (you don't import DllMain and window messages are not encoded) but I just wanted to show some examples I knew on top of my head without having to search for actually relevant samples (there probably aren't many, but they probably exist)

**Comment by sotteson1** [comment]
I'm going to close it for the various reasons listed above: different projections have different desires, and it's hard to know how to generically handle the word "reserved" as it can mean different things in different situations.
