### ISSUE TITLE
IOleUILinkContainerW has no GuidAttribute

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#359]
The `IOleUILinkContainerW` interface appears to be COM based (it derives from `IUnknown`) but it has no `GuidAttribute`. Is this a scraper bug?

**Comment by sotteson1** [comment]
This is a weird one. It really doesn't have a guid--there isn't one to scrape anywhere in the headers. The user implements the interface and the passes it to the API. The OS doesn't need to do a QI on the pointer because it's only doing the one thing with it.

```C#
public struct OLEUICHANGESOURCEW
{
...
    public IOleUILinkContainerW lpOleUILinkContainer;
...
}
```

**Comment by AArnott** [comment]
Ok. I wonder if .NET will create a CCW for an interface that has no guid. I guess I'll assume it does till someone files a bug.

**Comment by weltkante** [comment]
>  I wonder if .NET will create a CCW for an interface that has no guid.

How do you define the interface, in my experience using `ComImport` without a `Guid` on the interface I get compiler errors.

If you are not adding ComImport you are relying on the implicit assembly-wide default of `ComVisible(true)`, which means the runtime will generate a namespace based GUID for the type since its assumed its being defined by the assembly.

**Comment by AArnott** [comment]
>  In my experience using ComImport without a Guid on the interface I get compiler errors

I don't emit `[ComImport]`. There's no reason to. Unless it is in an embeddable assembly such that I want to activate type equivalence, there is no reason to emit this attribute.

> For other interfaces not specifying ComImport can be a huge issue, but I'll have a look later how the new generator looks like and if it has issues comment over there

I haven't seen any issue. And COM interop works fine in the spell checker sample without it.

**Comment by AArnott** [comment]
> If you are not adding ComImport you are relying on the implicit assembly-wide default of ComVisible(true)

No I'm not. Even with this set in a project, COM still works:
```cs
[assembly: ComVisible(false)]
```

**Comment by weltkante** [comment]
on topic, for `IOleUILinkContainerW` the zero GUID you generate works as far as I can tell

> COM still works

Not for me, I'm getting exceptions from the marshaling layer due to missing ComImport attribute (goes away if I copy/paste the generated source and add ComImport). Will create an isue on cswin32 once I simplify my code to a repro scenario that makes sense.

**Comment by AArnott** [comment]
> Not for me, I'm getting exceptions from the marshaling layer due to missing ComImport attribute (goes away if I copy/paste the generated source and add ComImport). 

Very strange.

> Will create an isue on cswin32 once I simplify my code to a repro scenario that makes sense.

Sounds good.
