### ISSUE TITLE
Unnecessary packing 

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#380]
The `MINIDUMP_INCLUDE_MODULE_CALLBACK` struct has a packing of 4 even though it only has a single field. It should not have any packing set. Rust warns about this.

**Comment by elachlan** [comment]
Do we just add `MINIDUMP_INCLUDE_MODULE_CALLBACK=[StructLayout(LayoutKind.Auto, Pack = 0)]` to `emitter.settings.rsp` to remove it?

**Comment by AArnott** [comment]
We should probably do something more general than fix just this one, @elachlan.

**Comment by mikebattista** [comment]
Closing out this stale issue. No infrastructure changes blocking right now. Can revisit if more cases are filed that justify a more general fix.

**Comment by tannergooding** [comment]
It's worth noting that Rust's warning on this is incorrect because packing impacts not only padding between its own members, but also the padding between the struct and surrounding members if it is itself a field in a struct.

The following [godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:39,endLineNumber:26,positionColumn:39,positionLineNumber:26,selectionStartColumn:39,selectionStartLineNumber:26,startColumn:39,startLineNumber:26),source:'%23include+%3CWindows.h%3E%0A%23include+%3Cpshpack4.h%3E%0A%0Astruct+MINIDUMP_INCLUDE_MODULE_CALLBACK1+%7B%0A++++ULONG64+BaseOfImage%3B%0A%7D%3B%0A%0A%23include+%3Cpoppack.h%3E%0A%0Astruct+MINIDUMP_INCLUDE_MODULE_CALLBACK2+%7B%0A++++ULONG64+BaseOfImage%3B%0A%7D%3B%0A%0Astruct+Test1+%7B%0A+++BYTE+x%3B%0A+++MINIDUMP_INCLUDE_MODULE_CALLBACK1+y%3B%0A%7D%3B%0A%0Astruct+Test2+%7B%0A+++BYTE+x%3B%0A+++MINIDUMP_INCLUDE_MODULE_CALLBACK2+y%3B%0A%7D%3B%0A%0Aunsigned+M1()+%7B+return+offsetof(Test1,+y)%3B+%7D%0A%0Aunsigned+M2()+%7B+return+offsetof(Test2,+y)%3B+%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:34.24298014045191,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:vcpp_v19_latest_x64,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x64+msvc+v19.latest+(Editor+%231)',t:'0')),k:41.26329658304439,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x64+msvc+v19.latest',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x64+msvc+v19.latest+(Compiler+%231)',t:'0')),k:24.49372327650371,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4) example gives a more concrete visualization of this.

That is the following code:
```cpp
#include <Windows.h>
#include <pshpack4.h>

struct MINIDUMP_INCLUDE_MODULE_CALLBACK1 {
    ULONG64 BaseOfImage;
};

#include <poppack.h>

struct MINIDUMP_INCLUDE_MODULE_CALLBACK2 {
    ULONG64 BaseOfImage;
};

struct Test1 {
   BYTE x;
   MINIDUMP_INCLUDE_MODULE_CALLBACK1 y;
};

struct Test2 {
   BYTE x;
   MINIDUMP_INCLUDE_MODULE_CALLBACK2 y;
};

unsigned M1() { return offsetof(Test1, y); }

unsigned M2() { return offsetof(Test2, y); }
```

Gives you:
```asm
unsigned int M1(void) PROC ; M1
  mov eax, 4
  ret 0
unsigned int M1(void) ENDP ; M1

unsigned int M2(void) PROC ; M2
  mov eax, 8
  ret 0
unsigned int M2(void) ENDP ; M2
```
