### ISSUE TITLE
Enums having to be passed as u32

### ISSUE THREAD

**Issue by 1Dragoon** [microsoft/win32metadata#397]
Kind of a minor issue as it is easy to work around, but I've noticed that in the examples, such as overlapped, enums can be passed directly, however for the AD structs I've been noodling with require them to be passed as u32. So for example, on the ADsOpenObject struct:

https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/ActiveDirectory/fn.ADsOpenObject.html

dwreserved expects a u32 instead of ADS_AUTHENTICATION_ENUM as documented here:

https://docs.microsoft.com/en-us/windows/win32/api/adshlp/nf-adshlp-adsopenobject

so I have to pass it as i.e. `ADS_AUTHENTICATION_ENUM::ADS_SECURE_AUTHENTICATION.0 as _` instead of just the enum

Yet in a similar situation with CreateFileA, the params that accept an enum in the rust crate are listed as dword in the API documentation:

https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea

I've seen many of these in different places. Is this a metadata issue or is it something in the rust crate that needs to be implemented? Or is this just the expected behavior? Pardon my naiveté as I'm still learning and I still don't even consider myself to be a software developer yet :)

**Comment by mikebattista** [comment]
@sotteson1 / @AArnott is our tooling to generate and apply more enums missing a pattern here?

**Comment by AArnott** [comment]
It sounds like the OP is pointing out we define enums where the headers did not, and it's causing inconvenience.
Adding enums where you used to see u32 or `DWORD` is by design, as it generally is expected to make the APIs easier to use. If you find cases where the enums make it harder to use, I don't understand why from your post, but I don't know rust.

**Comment by 1Dragoon** [comment]
Not sure what you mean; I'd prefer if the api indicated it needed an enum, that way intellisense can make it obvious without having to not only look up the rust api, but then go back further and look up the original win32 api documents. Development workflow would thus be much faster if these DWORD's were properly indicated as enums.

**Comment by AArnott** [comment]
ah, ok. I was reading it backwards. 

@mikebattista these missing enums can't be scraped from the docs automatically.

**Comment by mikebattista** [comment]
@AArnott / @kennykerr what I read was that functions like CreateFile where we have added enums work as expected, you can pass the enum directly. However, for APIs like ADsOpenObject, we have defined enums, but you can't pass them in directly, you need to cast them. The dwReserved parameter in this case is a dword like other places where we've added enums, but instead of being projected as the enum, it is projected as u32.

Is there a reason why this API is being treated differently than other APIs? This sounds like a bug.

**Comment by mikebattista** [comment]
@AArnott it looks like we've defined the enums, but haven't applied them to the function signature in this case.
