### ISSUE TITLE
RtlCaptureContext and RtlCaptureContext2

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#411]
`RtlCaptureContext` is in the `Debug` namespace, along with other RtlXxx functions while `RtlCaptureContext2` is in the `SystemServices` namespace, along with some other RtlXxx functions.

The RTL functions are part of the Windows kernel APIs, so perhaps these should be removed and added to the WDK winmd. #401

**Comment by mikebattista** [comment]
I think they should stay in this winmd for now. My recommendation would be moving them all to Windows.Win32.System.Kernel.

I think the cleanest way to do this would be to move winnt.h and rtlsupportapi.h to the Kernel partition, rather than continue to manually remap Rtl* functions as is currently being done.

@sotteson1 what do you think? Other than Rtl functions, most of what's in winnt.h are inlines and things that aren't getting emitted anyway.

**Comment by mikebattista** [comment]
I moved RtlCaptureContext2 next to RtlCaptureContext. The rest of the Rtl* functions in SystemServices and WindowsProgramming will get refactored as part of #388 and #456 .
