### ISSUE TITLE
Switch to semantic versioning for the metadata package

### ISSUE THREAD

**Issue by mikebattista** [microsoft/win32metadata#419]
Since we now include API versioning in the metadata and have decided to effectively follow a "latest head" model with one package that we continuously update, we should switch to semantic versioning for the metadata package.

We can aggressively make breaking changes now before 1.0, but we'll need a safe breaking change strategy after that so we can continue to innovate and improve. Semantic versioning provides that.

**Comment by sotteson1** [comment]
Since we already have packages that start at 10.0.19041.5, we can't really go backward to something less than that. Otherwise it will look like the older package are better (newer). So, I'm going to change the assembly version to be 10.0.19041.*-preview, where '*' increases with every build. This will make the assembly version unique for every build. @mikebattista, I could also start with something like 10.1.*-preview, or 11.*-preview. What would you prefer?

**Comment by mikebattista** [comment]
I'd like to switch to 0.* while we're in preview and then follow semantic versioning going forward.

**Comment by sotteson1** [comment]
> I'd like to switch to 0.* while we're in preview and then follow semantic versioning going forward.

The problem is we've already posted nuget packages of 10.0.19041.5-preview.*, so any new packages with lower version numbers (like 0.*) will show up below them. I think we're stuck with using higher numbers than 10.0.19401.5. We can still use semantic versioning, but we have to start with the larger numbers.

**Comment by AArnott** [comment]
> change the assembly version to be 10.0.19041.-preview

Assembly versions are 4 integers. They do not get a `-preview` suffix. Were you perhaps thinking of the *NuGet package version*?

May I suggest we utilize Nerdbank.GitVersioning to supply the ever-increasing number without you having to check in a version number change to get it to build that?

**Comment by mikebattista** [comment]
Per offline discussion, since there doesn't seem to be anything creative we can do to restart from 0.*, we can switch to `10.1.X.X-preview` going forward until we hit our first stable release. We'll increment the minor version for breaking changes until that point. Once we go stable, we'll remove the `-preview` suffix and start incrementing the major version beyond 10 when there are breaking changes.

**Comment by sotteson1** [comment]
> > change the assembly version to be 10.0.19041.-preview
> 
> Assembly versions are 4 integers. They do not get a `-preview` suffix. Were you perhaps thinking of the _NuGet package version_?
> 
> May I suggest we utilize Nerdbank.GitVersioning to supply the ever-increasing number without you having to check in a version number change to get it to build that?

We're using the "counter" variable feature in Azure DevOps to increase the last integer with every build. Is that similar to Nerdbank.GitVersioning?

**Comment by sotteson1** [comment]
> Per offline discussion, since there doesn't seem to be anything creative we can do to restart from 0.*, we can switch to `10.1.X.X-preview` going forward until we hit our first stable release. We'll increment the minor version for breaking changes until that point. Once we go stable, we'll remove the `-preview` suffix and start incrementing the major version beyond 10 when there are breaking changes.

I've switched it to be 10.1.X-preview on the NugetPackage, and the assembly version is 10.1.X.0.

**Comment by AArnott** [comment]
> We're using the "counter" variable feature in Azure DevOps to increase the last integer with every build. Is that similar to Nerdbank.GitVersioning?

Meh, not really. AzDO is just a dumb incrementer. Building the same commit twice will produce two unique versions, and you can't predict it from a dev box. NB.GV will deterministically compute the incrementing number from the "git version height", so each commit is essentially assigned a unique version. It also can burn the version info and commit id into the compiled dll's so that it's always trivial to jump from source code commit to dll version and vice versa.
None of this is done by AzDO, and once a build log is removed from AzDO, you cannot even make the leap between these manually.

**Comment by sotteson1** [comment]
> Meh, not really. AzDO is just a dumb incrementer.

Cool, I'll check out Nerdbank.GitVersioning.
