### ISSUE TITLE
Missing dbgeng.h and wdbgexts.h

### ISSUE THREAD

**Issue by jopletchMSFT** [microsoft/win32metadata#462]
I was interested in writing a windbg extension using windows-rs. However, it looks like nothing from `wdbgexts.h` or `dbgeng.h` are currently generated (based on search [here](https://microsoft.github.io/windows-docs-rs/doc/bindings/index.html)).

**Comment by mikebattista** [comment]
Thanks. These are in our list of missing headers to add along with `DbgModel.h`.

Is that everything you'd need?

**Comment by jopletchMSFT** [comment]
Based on the example windbg extensions I've looked at, yes those are the only headers that are imported. This is just a fun side project for me and I haven't written a windbg extension before so it's possible I'd discover something later, but it seems kinda unlikely from here.

Thanks!

**Comment by mikebattista** [comment]
Ok. I added these headers. You can find them under Windows.Win32.System.Diagnostics.Debug once the Rust crate takes a metadata update.

We had to exclude SymbolSearchInfo, TypeSearchInfo, and EnumerateChildrenEx since they use C++-isms that can't be translated into the winmd. Let us know if that breaks the API or if the rest is still useful.
