### ISSUE TITLE
Add WSL API.

### ISSUE THREAD

**Issue by Berrysoft** [microsoft/win32metadata#463]
There's only enum `WSL_DISTRIBUTION_FLAGS` in namespace `Windows.Win32.WindowsSubsystemForLinux`.

Would you add APIs in [`wslapi.h`](https://docs.microsoft.com/en-us/windows/win32/api/wslapi/) header?

**Comment by mikebattista** [comment]
We are scanning the header but the APIs are being excluded for some reason.

I think it's because the DllImport attribute on the generated code is blank. If I add the apiset these come from manually like you see in the screenshot for the first one, they start showing up.

@sotteson, this seems like a bug in the DllImport tooling.


![image](https://user-images.githubusercontent.com/13860912/117490950-613cf380-af24-11eb-88c3-547385f2f3f6.png)


![image](https://user-images.githubusercontent.com/13860912/117491201-bb3db900-af24-11eb-9e96-50c8c0d67403.png)

**Comment by sotteson1** [comment]
It looks like the .lib isn't in the WinSDK for some reason, so we don't find the imports.

https://stackoverflow.com/questions/50865196/where-is-the-wslapi-lib-file

**Comment by mikebattista** [comment]
Can we workaround this in our tooling?

**Comment by sotteson1** [comment]
We just need to add lib entries for them in the partition's .rsp file.

**Comment by leoppro** [comment]
At the risk of asking, approximately when will this be fixed?

**Comment by mikebattista** [comment]
> We just need to add lib entries for them in the partition's .rsp file.

What does that change look like?
