### ISSUE TITLE
Add support for scraping constants defined with macros like IOCTLs from winioctl.h

### ISSUE THREAD

**Issue by coffeenotfound** [microsoft/win32metadata#464]
Right now it seems like some definitions for USN manangement are missing, especially the `FSCTL_*_USN_*` set of constants
I also noticed that `DeviceIoControl` takes `dwiocontrolcode` as an `u32` which seems oddly un-typesafe

Is this still a work in progress area or am I just missing the right keywords?

**Comment by mikebattista** [comment]
These and many others are all defined with macros like `#define FSCTL_ENUM_USN_DATA             CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 44,  METHOD_NEITHER, FILE_ANY_ACCESS) // MFT_ENUM_DATA`.

We don't currently scrape these, but @sotteson is planning to add support soon.

**Comment by mikebattista** [comment]
It seems there are several constants deliberately excluded via `ConstantsScraper.rsp` because they are defined with macros.

As part of this change, we need to go back and remove any exclusions here that are no longer needed.

**Comment by sotteson1** [comment]
If I remember correctly, the exclusions are because sometimes constants are defined both a macro (which the constant scanner sees) and as a real constant which clangsharp sees. Or, the macros are more complicated than the scraper can deal with so we just manually define them in a .cs file and have the scraper ignore the macro.
