### ISSUE TITLE
Windows.Win32.winmd needs to be self-describing

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#472]
The winmd lacks the definitions of various attributes and types like `SupportedArchitecture` - everything in the `Windows.Win32.Interop` namespace is missing - so there's no way for tools to parse these attributes without a priori knowledge of them. WinRT metadata includes the definitions of all the attributes it defines in the `Windows.Foundation.Metadata` namespace. Win32 should do the same.

**Comment by AArnott** [comment]
I think it *is* self-describing. The Windows.Win32.winmd includes an assembly reference to Windows.Win32.Interop.winmd, which is also in the package and contains the types you say are missing.

**Comment by kennykerr** [comment]
Nice. I didn't look in the DLL because DLL implies code. 😊 

I think most languages are only parsing winmd files so won't pick this up. How about we just put those types in the winmd file?

**Comment by AArnott** [comment]
(corrected my comment above to properly specify the file extension).

**Comment by AArnott** [comment]
> I think most languages are only parsing winmd files so won't pick this up.

I don't know whether languages need to. CsWin32 has never had to open this file. I just find it useful to reference in ILSpy so I can see what values might be, but the metadata reader I'm using never had a need to access it at runtime.

> How about we just put those types in the winmd file?

I don't know... that sounds like work without proven benefit, which may reduce benefit from time spent elsewhere. What are we gaining if we do that work?

**Comment by kennykerr** [comment]
Consistency and discoverability. WinRT includes the metadata in its winmd. Win32 does not. Agreed, there's no need for this at runtime (in most languages but perhaps JS will need it...) but then there's no need for Windows.Win32.winmd at runtime either. Having everything that describes the Win32 APIs in a single winmd is nevertheless valuable. The whole point of the Windows.Win32.winmd is to describe the Win32 API - this is part of that description.

Not too terribly urgent but I think its important that we continue to improve the quality and consistency of the metadata. There are still a lot of things that are wildly different between the Win32 and WinRT metadata and while we cannot necessarily solve them all, every bit helps.

**Comment by AArnott** [comment]
> Agreed, there's no need for this at runtime ... but then there's no need for Windows.Win32.winmd at runtime either.

By "runtime" I was referring to code generation time. I agree neither file is necessary at application runtime. I also don't expect the `Windows.Win32.Interop.dll` file to be required to create a projection.
So basically I see Windows.Win32.Interop.dll as a documentation file to help the projection author understand how to write code to interpret what is in the winmd, which _is_ required at generation time.

> its important that we continue to improve the quality and consistency of the metadata

Sure. I don't see this as inconsistent because the winmd carries info from the headers and the dll contains a few attributes that explain how to interpret that data. Consistency does not require that all data be in one file, and drawing a line between two files where one file must be deployed to generate code and the other doesn't seems perfectly reasonable to me.

That's all I'll say about this, since I'm ok with it either way. I would just rather see Steve's time spent on fixing things that make a difference to the projections or end users, and I don't think this is one of those things.

**Comment by kennykerr** [comment]
It's not a showstopper either way.

**Comment by sotteson1** [comment]
Windows.Win32.Interop.dll acts like Windows.Foundation.FoundationContract.winmd which contains the attributes that the other contracts use. I don't care if we need to change the extension from DLL to winmd but I don't see the point either since like Andrew said it's not used for projections. The Windows contracts reference other System DLLs like System.Runtime.WindowsRuntime.dll, so a winmd referencing DLLs isn't a problem. For sure I won't be moving the attributes into Windows.Win32.winmd.

**Comment by kennykerr** [comment]
Feel free to close this issue if you disagree. 😊 

I just brought it up because a few of us struggled to get started with some of the newer features because the metadata isn't self-describing. It's just a usability issue. You can fix the usability issue by renaming the dll to a winmd or by including it in a single winmd. Many projects just grab the latest winmd out of the nuget package and ignore the rest. It would just be simpler for all of those projects if it were a single winmd. But again your choice. Now that I know where to find the attributes I'm unblocked. 

By the way, `Windows.Foundation.FoundationContract.winmd` contains a lot more than just the attributes - without it no language projection could ever function correctly.

Anyway, that's just my experience. No worries if you feel differently.

**Comment by sotteson1** [comment]
There will be other .winmd's that reference Windows.Win32.Interop just for the attributes, and it wouldn't make sense for them to have to carry around the big 12MB .winmd when all they need are the attributes. I'm closing this because the scraped metadata and the attributes were intentionally separated.
