### ISSUE TITLE
VK_ constants are defined as UInt32 instead of UInt16

### ISSUE THREAD

**Issue by jnm2** [microsoft/win32metadata#489]
https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-keybdinput defines `WORD vVk` and the docs for the parameter link to https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes which defines all the constants. the docs also say "The code must be a value in the range 1 to 254."

Impact: I have to use `{ wVk = (ushort)VK_RETURN }` instead of `{ wVk = VK_RETURN }` in C#.

**Comment by mikebattista** [comment]
@sotteson is this something we can address in the constant scraper? Or do we need to manually remap the type for each of the constants?

**Comment by simonbuchan** [comment]
Also, `WAVE_FORMAT_PCM` (should be u16 for use in `WAVEFORMATEX::wFormatTag`), several others...

**Comment by weltkante** [comment]
VK constants are byte sized, which is obvious from their declaration and mentioned occasionally in the API descriptions where its used, for example in [VkKeyScanA ](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-vkkeyscana) which says the VK constant is returned in the low byte, or in [GetKeyboardState](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeyboardstate) which explicitely says VK constants are indexing into a 256-byte array

**Comment by mikebattista** [comment]
As part of adding these to an enum in #551, I changed the type to ushort.

**Comment by weltkante** [comment]
> As part of adding these to an enum in #551, I changed the type to ushort.

@mikebattista type is byte as I explained [above](https://github.com/microsoft/win32metadata/issues/489#issuecomment-860141943)

**Comment by mikebattista** [comment]
XInput VKs are much greater than 256.

**Comment by weltkante** [comment]
That doesn't change the fact that the `VK_` constants of the win32 API are supposed to be bytes ...

if XInput also uses the VK prefix it shouldn't be in the same enum in the first place, because its constants will not be compatible with the win32 API

**Comment by mikebattista** [comment]
XInput is part of the Win32 API. I put them in separate enums for other reasons, but can you pass an XInput VK to SendInput? Can you also use the base VKs with the XInput APIs?

**Comment by weltkante** [comment]
Not sure how to name the "base API" if not win32 - maybe call it winuser after the header the API is coming from? XInput comes from the DirectX family of APIs which for me mentally is not part of win32 but a separate API set (historically you had to install it separately after all), maybe I'm having the wrong mental model here. XInput may be reusing the winuser definitions and extending them, but that doesn't mean everyone magically understands this extension.

I don't know about SendInput (not been using it very much) but I'm pretty sure the other keyboard APIs from winuser are incompatible because they use the higher bytes for other information like modifier states, see the link to [VkKeyScan](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-vkkeyscana) I gave above for one example.

**Comment by mikebattista** [comment]
We're not talking about anything undocumented here.

@sotteson1 what would you recommend here for the type? There are already two enums and we can change the winuser type to byte if that's correct, but it's not clear yet if that's right.
