### ISSUE TITLE
Foundation

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#518]
I like how the new Foundation namespace in the latest release has a very short list of types. 

But I noticed this namespace also has a huge number of constants. Was that intentional? They seem unrelated to any of the types in this namespace.

**Comment by riverar** [comment]
@kennykerr Is the proposed action here is to move the `NTSTATUS` and `HRESULT` constants into their respective namespaces? And keep the overlap (e.g. `STATUS_SUCCESS`) in Foundation?

**Comment by mikebattista** [comment]
The constants are from winerror.h and ntstatus.h which were previously parked over in either SystemServices or WindowsProgramming, which I'm trying to get rid of.

These files contain error codes for all APIs basically. Many should be manually remapped to be with the corresponding API (like WININET_*). Many look like common error codes that could be used by many APIs.

Until we can get through and manually remap everything inside these header files, I moved the headers over to Foundation as a starting point to get them out of where they were, since any common errors left over after remapping individual ones I'd probably want in Foundation, and moving the headers to that partition is how I would do that.

If you think we should move these somewhere else in the meantime, I'm open to suggestions but don't want to leave them in SystemServices or WindowsProgramming.

**Comment by kennykerr** [comment]
Ah, I didn't realize they were just the constants for those types defined in the Foundation namespace. I guess that's fine. I was just surprised to see such a huge list of constants in what I thought would have been a relatively small namespace. 

Feel free to close this issue. The rest is just observations. Feel free to ignore. 

I still find it confusing that some constants are defined as fields of the Apis class (e.g. HRESULT constants) and others as fields of the respective types (e.g. WIN32_ERROR constants). Seems like HRESULT and NTSTATUS should be modeled more like WIN32_ERROR if you're going to define them all in one place anyway.

**Comment by mikebattista** [comment]
HRESULTS are an open set as well which makes an enum less appropriate.

I'm going to keep these in Foundation for now. For obvious constants like WININET_* that could be mapped easily to other existing namespaces, we can move those over. In the meantime, I'd rather keep these headers in Foundation to get them out of SystemServices and WindowsProgramming, until we get around to refactoring individual constants.
