### ISSUE TITLE
Embed api docs inside of winmd files.

### ISSUE THREAD

**Issue by AraHaan** [microsoft/win32metadata#544]
So the winmd files are now arch specific with the docs not embeded inside of the winmd files to fix https://github.com/microsoft/CsWin32/issues/38 which could emilinate the need to depend on YamlDotNet which then fixes this issue https://github.com/microsoft/CsWin32/issues/221 when using the generator to generate code while using an analyzer that depends on an older version of YamlDotNet which blows up because that gets loaded first and analyzers and generators do not get loaded into separate contexts (AssemblyLoadContext's) which is another separate issue.

I think embedding the docs for each api somehow in the winmd themselves to where they can grab without needing to do any I/O to retrieve them would be the best bet here to fix this issue (at least for C# / managed side of things).

There would be benefits for this:
- the docs would be per arch to reflect only the apis in each winmd file
- the docs would be emitted for all languages instead of language specific and needing to emit them done on the user side of things using external libraries
- overall cleaner throughout and less needless dependencies that can overall optimize performance as well (in CSWin32 and in generator you can look at speed improvements in the IDE itself when generating code as it is known (they have a filed issue in that repository which is https://github.com/microsoft/CsWin32/issues/244) that it can slow the VS2019 IDE to a crawl due to the nature of relying on YamlDotNet to process the docs). Doing this could avoid the slowdown entirely.

**Comment by mikebattista** [comment]
There's only 1 winmd file. The APIs are decorated with custom attributes for architecture-specific designs where appropriate.

The preference from early projection authors was to not include documentation in the winmd for size, performance, and other concerns. Our current plan is to genericize the documentation parser from C#/Win32 so that all projections can provide a similar experience. This would still be detached from the winmd but it should be easy for projections to get to the documentation for a specific API in the winmd.

The dependency on YAML might go away as part of that effort.

**Comment by AArnott** [comment]
Embedding the docs in as assembly already happens in CsWin32. There is no perf gain to be had from that. The perf gain will be from changing the format of those docs from YAML to a binary indexed representation so that parsing the entire YAML file at startup is no longer required. This perf work is already tracked in https://github.com/microsoft/CsWin32/issues/38.

But [as I mentioned to you earlier](https://github.com/microsoft/CsWin32/issues/38#issuecomment-865289457) the plan is *also* to move the docs to a separate package, produced by this repo. 

As this work is already tracked, I'm going to close this issue.
