### ISSUE TITLE
Scrape docs for constants

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#563]
The `WM_PAINT` constant [is documented](https://docs.microsoft.com/en-us/windows/win32/gdi/wm-paint) but does not appear to be included in the Win32Docs package. 
Lets get this (and all other constants) included in the scraper (and verify that CsWin32 uses it).

The WM_PAINT constant is documented in a repo we don't scrape right now: https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src/gdi/wm-paint.md
We scrape the MicrosoftDocs' `sdk-api` repo only -- not `win32`.

**Comment by timsneath** [comment]
Thanks for filing this, Andrew! 

And of course, `WM_PAINT` is a bit of an outlier, since it's a constant that happens to have its own page dedicated to it. We should also be including constants like these: https://docs.microsoft.com/en-us/windows/win32/api/uxtheme/nf-uxtheme-getthemesyscolorbrush or these: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowpos

There are many tables like this in the documentation. One wrinkle is that some constants are documented multiple times in different pages.

**Comment by AArnott** [comment]
Yes, such constants that are documented on the page describing the API that uses them are automatically picked up by the scraper already and we even used this code to suggest enums around constants.

**Comment by sotteson1** [comment]
All the constants mentioned on this issue are in the metadata, so I'm closing this issue. If there are more we missed, please add issues for them.
