### ISSUE TITLE
mention that `PWSTR` and `PSTR` are strings

### ISSUE THREAD

**Issue by smasher164** [microsoft/win32metadata#589]
`PWSTR` and `PSTR` are `uint16_t*`. Is it possible to extend the metadata with info that they are string-like?

@tdakkota notes in https://github.com/golang/go/issues/43838#issuecomment-887272645 that setting a `TypeAttribute` of `AnsiClass`/`UnicodeClass` or giving it `ELEMENT_TYPE_STRING` are possibilities.

Currently, [`windows-rs`](https://github.com/microsoft/windows-rs/blob/61ed91e31ce7c181d570257a793f8dd3a9df92d6/crates/gen/src/types/pwstr.rs#L37-L47) and [`zigwin32gen`](https://github.com/marlersoft/zigwin32gen/blob/b63c76ee2f070dbb3cb027484c194f61316b9eb2/src/pass1.zig#L132-L138) maintain a list of well-known types to deal with these.

**Comment by weltkante** [comment]
> Currently, windows-rs and zigwin32gen maintain a list of well-known types to deal with these.

That probably can't be avoided. Nothing against annotating `PWSTR` and `PSTR` but there are other string-like types (probably mostly in the APIs involving COM) which require usage of specific allocators and string manipulation functions, so projections always have to special case these. Need to chose the semantic of being a "string-like type" very carefully for it to have any value, otherwise it provides no gain if you still have to differentiate between the different string types in the projection.

**Comment by smasher164** [comment]
> you need to chose the semantic of being a "string-like type" 

Right. This doesn't need to be a single piece of metadata. I think it would be useful to know information about the expected string, like whether it's null-terminated, its encoding, etc...

**Comment by marler8997** [comment]
Since I think these are the only 2 types the metadata uses to represent strings (i.e. pointers to null-terminated arrays), I don't see a benefit to creating new attribute for this.  Unless there are more types that would use these new attributes?  Otherwise, checking for the specially named types `PSTR` and `PWSTR` wouldn't be much different than checking for a new "string-like" attribute.

**Comment by mikebattista** [comment]
@sotteson1 @kennykerr what are your thoughts on this? If WinRT is using ELEMENT_TYPE_STRING, should we be using it here?

**Comment by kennykerr** [comment]
That is already used by WinRT to represent HSTRING so that would be incompatible with language projections that support both WinRT and Win32. What we have now is a reasonable compromise to support both.

**Comment by mikebattista** [comment]
> That probably can't be avoided. Nothing against annotating PWSTR and PSTR but there are other string-like types (probably mostly in the APIs involving COM) which require usage of specific allocators and string manipulation functions (i.e. not just a zero terminated sequence of characters), so projections always have to special case these.

BSTR is one such example, right?

> That is already used by WinRT to represent HSTRING so that would be incompatible with language projections that support both WinRT and Win32. What we have now is a reasonable compromise to support both.

Ok. Is this a Won't Fix? Or is there anything we can/should do here?

**Comment by kennykerr** [comment]
We already have types for PSTR, PWSTR, BSTR, and so on. I don't there's anything to do here. Language projections must deal with these "well-known" types.
