### ISSUE TITLE
OBJID_WINDOW not available?

### ISSUE THREAD

**Issue by Lalaland** [microsoft/win32metadata#594]
OBJID_WINDOW and the other object identifiers don't seem to be available?

**Comment by mikebattista** [comment]
I think we should have an OBJECT_IDENTIFIERS enum that has everything from https://docs.microsoft.com/en-us/windows/win32/winauto/object-identifiers.

Then we should apply that enum wherever a function expects any of those (e.g. GetScrollBarInfo or GetMenuBarInfo). Since we need unique enum member names, I'd rather not try to create separate enums for each use case that only contains the subset of supported values, since we'll run into overlap with members like OBJID_CLIENT.

What do you think?
