### ISSUE TITLE
STILL_ACTIVE not reflected in metadata

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#616]
Not sure how you want to proceed with this one. `GetExitCodeProcess` [is documented as possibly returning `STILL_ACTIVE`](https://docs.microsoft.com/en-gb/windows/win32/api/processthreadsapi/nf-processthreadsapi-getexitcodeprocess?redirectedfrom=MSDN&WT.mc_id=WD-MVP-5002756#remarks), which is now a macro for `STATUS_PENDING` (minwinbase.h).

Should the metadata add these _constants_ to align with documentation? Or should we get the docs updated to point to `STATUS_PENDING`?

**Comment by kennykerr** [comment]
Probably a doc update would be simpler (less code baggage)? What does @stevewhims think?

**Comment by stevewhims** [comment]
FWIW, I've added a mention of STATUS_PENDING to that topic. I couldn't find an actual *topic* for STATUS_PENDING, so I'm mentioning rather than pointing to. There are other topics in this feature area that mention STILL_ACTIVE, so they might need similar edits. @KB (Karl-Bridge-Microsoft) owns this topic, so mentioning him FHI.

**Comment by mikebattista** [comment]
Fixed with #751.
