### ISSUE TITLE
Proposal: Emit DllImport attribute w/ lowercase dllname

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#648]
I am proposing that all `DllImport` attributes always be emitted with its dllname in lowercase form. This, I believe, aligns more closely with lib naming practices on non-Windows platforms (where cygwin, mingw, etc. are in use). It also removes the burden on bindings authors to individually handle this.

The Rust crate, for example, [transforms all names at compilation time](https://github.com/microsoft/windows-rs/pull/1128) to support cross-compilation scenarios.

Example in metadata today:
```csharp
[DllImport("KERNEL32", ExactSpelling = true, SetLastError = true)]
[SupportedOSPlatform("windows8.0")]
public unsafe static extern HANDLE CreateFile2(
  [In][Const] PWSTR lpFileName,
  [In] FILE_ACCESS_FLAGS dwDesiredAccess,
  [In] FILE_SHARE_MODE dwShareMode,
  [In] FILE_CREATION_DISPOSITION dwCreationDisposition,
  [Optional][In] CREATEFILE2_EXTENDED_PARAMETERS* pCreateExParams);
```

**Comment by kennykerr** [comment]
I would avoid doing this because a binary is often built using different libraries that may import functions from the same DLL and preserving the case that the umbrella libs originally used avoids multiple libraries showing up in the import table. 

<img width="601" alt="image" src="https://user-images.githubusercontent.com/9845234/153478333-d4ce16ef-29c5-4865-8a34-c9ec4a01cf7d.png">

The cross-compilation scenario will also soon disappear as it moves to lib-free linking.

**Comment by riverar** [comment]
I don't think the import table impact is relevant, but will concede the primary motivator for this proposal was due to lack of `raw_dylib` in Rust. Now that it's landing soon 🎉, the functionality proposed here is no longer needed.

I'll close this for now to cleanup the repository, but strongly encourage **D, Dart, and Zig** folks to speak up if they're impacted.
