### ISSUE TITLE
GetSystemFirmwareTable enum missing

### ISSUE THREAD

**Issue by AArnott** [microsoft/win32metadata#658]
The [GetSystemFirmwareTable](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemfirmwaretable) method takes a very bizarre first parameter which is typed as a 32-bit integer but accepts one of 3 values created by putting 4 ascii characters together. 
These should be an enum for easy access:

```cs
public enum FirmwareTableProviders
{
    ACPI = 1094930505,
    FIRM = 1179210317,
    RSMB = 1381190978,
}
```

**Comment by KalleOlaviNiemitalo** [comment]
What's the policy on singular vs. plural in names of non-Flags enum types?

**Comment by AArnott** [comment]
Good question. I don't know what policy we adopted in this repo. The name of the enum I gave above is just an idea.

**Comment by riverar** [comment]
This is less bizarre in the context of ACPI.

The docs indicate the first parameter _can_ be one of those values, but this can be any signature value [1] (e.g. `FACP`, `MCFG`, `APIC`, `HPET`) including values outside the specification [2].

If you're going to create an enum for the supported values, please do include all the values per ACPI 6 specification. Otherwise (and my recommendation) perhaps just leave it defined as uint32 or uchar[4].

[1] https://uefi.org/specs/ACPI/6.4/05_ACPI_Software_Programming_Model/ACPI_Software_Programming_Model.html#description-header-signatures-for-tables-defined-by-acpi
[2] https://uefi.org/specs/ACPI/6.4/21_ACPI_Data_Tables_and_Table_Def_Language/ACPI_Data_Tables.html#types-of-acpi-data-tables

**Comment by AArnott** [comment]
Oh, interesting. I think "can be one of the following values" is the same language they use for closed sets. If that's true that's too bad because it isn't clear which are open vs. closed sets. 

Yes, enums are probably best used for closed sets of values. But maybe the metadata can define constants for these at least.

**Comment by KalleOlaviNiemitalo** [comment]
@riverar, wouldn't those `FACP`, `MCFG`, `APIC`, `HPET`, etc. go in the second parameter `DWORD FirmwareTableID`, rather than the first parameter `DWORD FirmwareTableProviderSignature`?

**Comment by riverar** [comment]
Yep, good catch.

@AArnott 's original ask stands. Although now I'd like to see that signature parameter also get a friendly enumeration treatment too!

**Comment by mikebattista** [comment]
So FirmwareTableProviderSignature should use constants rather than an enum? And FirmwareTableID should be an enum with members like FACP = PCAF (in ASCII)?

For the latter, should it contain all the values from table 5.5 and 5.6 in the [spec](https://uefi.org/specs/ACPI/6.4/05_ACPI_Software_Programming_Model/ACPI_Software_Programming_Model.html#description-header-signatures-for-tables-defined-by-acpi)?

**Comment by AArnott** [comment]
No constants. Just the enum originally asked for for the first parameter. 
The second parameter takes data obtained from another API so no constants should be required for that, and an enum would suggest a closed set, which isn't the case for the second parameter.

**Comment by riverar** [comment]
Agreed.
