### ISSUE TITLE
`SupportedArchitecture` dependency issue

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#725]
I just tried turning on multi-arch support in Rust and hit a problem with the `DISPATCHER_CONTEXT_ARM64` struct. The metadata says it is available on x86 and x64 but it has a field of type `UNWIND_HISTORY_TABLE` that is only available on x64 and ARM64, breaking x86 builds.

https://github.com/microsoft/windows-rs/runs/4109751749?check_suite_focus=true

**Comment by AArnott** [comment]
There are actually a good many such 'transitive' limitations in the metadata today. The metadata only attributes the direct APIs that are different in each architecture.

For CsWin32 I generate the code recursively (as I expect you do) based on type references and if _any_ of the dependencies aren't available given the target architecture, I bail out and tell the user the API the originally requested is not available on their platform.
I like this approach much better than asking the metadata to apply the attribute to all types/methods that reference a platform-specific type because as it is, a user can write their own cross-platform compatible definition of the struct, and then CsWin32 will skip generating it and succeed at generating other types that reference it, even on an AnyCPU platform.

So, rather than change the metadata here, how do you feel about adopting the same defensive recursion technique employed by CsWin32?

**Comment by kennykerr** [comment]
Thanks for the feedback. The Rust generator has two modes. The first mode works much the way you describe and generates just what is needed. That mode could conceivably elide APIs that aren't fully/correctly formed. But the second mode (and more widely used) generates everything ahead of time, including the code for all architectures. This is more like what you might see in a C++ generator where everything is generated with `#ifdef` blocks to deal with multiple definitions of the same API for different architectures. In this mode I don't know ahead of time what architecture the generated code is targeting. 

Regardless of approach, it still seems to me that this is bug in the metadata and not merely a limitation, even if it happens to work for the C# generator. It definitely seems to prevent ahead of time code generators (like a C/C++ header files) from working at all.

**Comment by sotteson1** [comment]
> Regardless of approach, it still seems to me that this is bug in the metadata and not merely a limitation, even if it happens to work for the C# generator. It definitely seems to prevent ahead of time code generators (like a C/C++ header files) from working at all.

Yep, it's a bug in the metadata we can fix. I should be able to come up with a test that prevents this kind of thing in the future.

**Comment by AArnott** [comment]
@sotteson1 Can you make it clear in the metadata which attributes are because the specific struct or method is only exposed in one architecture vs. a transitive dependency not being available so CsWin32 can continue delivering the flexibility that it does today?

**Comment by sotteson1** [comment]
> @sotteson1 Can you make it clear in the metadata which attributes are because the specific struct or method is only exposed in one architecture vs. a transitive dependency not being available so CsWin32 can continue delivering the flexibility that it does today?

When I wrote the test to find other bugs like this one, only this one was found. In this case, DISPATCHER_CONTEXT_ARM64 should not be emitted at all, because it's used to typedef the arch-specific CONTEXT for arm64, but that should only happen for arm64. arm64 is already renaming DISPATCHER_CONTEXT_ARM64 to CONTEXT, and the other two should just exclude it.

**Comment by sotteson1** [comment]
Oh and @AArnott, if you know of other transitive dependencies, let me know. Maybe my test is missing some case that it shouldn't.
