### ISSUE TITLE
Consider splitting deprecated APIs into a separate winmd

### ISSUE THREAD

**Issue by mikebattista** [microsoft/win32metadata#727]
A single large winmd like Windows.Win32.winmd can result in degraded performance in some scenarios.

We could split deprecated APIs into a separate winmd like Windows.Win32.Deprecated.winmd within the same Microsoft.Windows.SDK.Win32Metadata package to improve performance in the majority scenarios while still keeping the APIs accessible to those who need them. This deprecated winmd would depend on the main winmd, but there would be no dependencies from the main winmd to the deprecated winmd.

Defining what qualifies as "deprecated" enough to go in here will take some iteration. We have some candidates to consider and would start conservatively with just those.

@AArnott @kennykerr @marler8997 @timsneath do you have any concerns with this approach?

@kennykerr has expressed support for this to improve the Rust projection.

**Comment by timsneath** [comment]
I have two reservations about this:

1. (Meant with the very best of intent!) What Microsoft considers "deprecated" isn't always exactly aligned with what customers actually use. Arguably this entire metadata file consists of APIs that have been deprecated at some point in the Windows 8 / 10 cycle :) There are some APIs that are clearly redundant and have been carried forward since Win16 days, but I suspect there are more gray areas than clear-cut cases. As someone who has been developing with Windows for thirty years, I don't think I'd feel confident about my own picking power, but perhaps you have some obvious cases that are sizable enough to merit the added complexity.
2. Finding types becomes harder, as I understand it. WinRT has the `RoGetMetaDataFile` API which resolves a type to a WinMD file, but in the absence of an equivalent Win32 API, I would have to do some kind of brute force search, which aside from the extra coding would likely impose an additional performance hit. (That's not true if you do a "perfect" job of deprecating only the APIs I don't care about, of course.)

So I guess, at least from my perspective, having a single .winmd file is just fine. The costs are all borne at the time of code generation, not by end-users, and changing this just means churn and extra code I have to write. If splitting is a requirement, I strongly appreciate your design approach of having a one-way reference. 

FWIW, I wouldn't vote against a split by SKU (i.e. moving server APIs like Index Server, IIS, Active Directory out of the main WinMD file)... it might be possible to make reasoned decisions about excluding those, since this layer of abstraction is baked into the product itself.

**Comment by AArnott** [comment]
What do you expect the customer impact of this change would be? Any at all? My initial thinking is that CsWin32 would just bring in both metadata packages and continue generating any API the customer asks for. Would there be value in doing anything different?

Eventually when we're talking about a monolithic assembly for .NET, I could see the monolith getting smaller and offering fewer APIs being potentially useful. 

But how would we deprecate APIs going forward? Any you _remove_ from win32metadata (to add to the deprecated one) constitutes a breaking change and if projections weren't picking up the deprecated metadata as well anyway, might result in build breaks until the user added the extra package.

**Comment by mikebattista** [comment]
Thanks. #1 is "defining what qualifies as 'deprecated' enough" that I mentioned. Agreed just because something has a newer replacement doesn't mean it's not still widely used and adopted, and a key goal of this project is to maintain source compatibility with all APIs and make them accessible to more languages.

For #2, I'll defer to others on how it would impact the projection authoring experience and resolution of types.

> FWIW, I wouldn't vote against a split by SKU (i.e. moving server APIs like Index Server, IIS, Active Directory out of the main WinMD file)... it might be possible to make reasoned decisions about excluding those, since this layer of abstraction is baked into the product itself.

Interesting idea. We are open to exploring other ways to split the winmds if we end up splitting at all.

@AArnott the proposal here would be to include this additional winmd in the same Microsoft.Windows.SDK.Win32Metadata NuGet package. Yes we should still generate any API that is requested and .NET developers should still be able to access these APIs in the future with prebuilt assemblies.

@kennykerr has expressed concern for some time over the size and performance of the winmd and could share some more details on the motivation here and if the benefits outweigh the added complexity.

**Comment by marler8997** [comment]
The full metadata bindings for Zig is 63 MB.  Because the language is analyzed "lazily", the size of the bindings isn't really an issue.  So the benefit would be in decreasing disk space/download size of the bindings themselves, which isn't as important as something that would significantly reduce compile times.

Taking only the Zig projection into account I don't think its worth splitting, but I can understand the need for the other projections.  Do we have any idea how much of the API would be considered deprecated?

**Comment by kennykerr** [comment]
The benefits/drawbacks are not yet immensely clear either way. As an additional point of reference, the WinRT metadata deprecates APIs via an attribute on the types/methods directly rather than splitting them into a separate winmd. That could be another possible approach, but again deciding what to deprecate is highly subjective.

**Comment by mikebattista** [comment]
If there weren't any performance concerns with a growing winmd, we'd use attributes for deprecation (see #403) and that would be enough.

The proposal to split is based solely on performance concerns, and splitting out "deprecated enough that is unlikely to be needed in most cases" is one potential boundary. @timsneath proposed another potential boundary of SKU.

We won't make any changes here until the benefits/drawbacks are better understood.

**Comment by mikebattista** [comment]
Closing out since I haven't heard any complaints in this area.
