### ISSUE TITLE
Missing ordinal annotations for COMCTL32 APIs

### ISSUE THREAD

**Issue by riverar** [microsoft/win32metadata#734]
Example:
```csharp
[DllImport("COMCTL32", ExactSpelling = true)]
[SupportedOSPlatform("windows5.1.2600")]
public unsafe static extern BOOL GetWindowSubclass([In] HWND hWnd, [In] SUBCLASSPROC pfnSubclass, [In] UIntPtr uIdSubclass, [Optional][Out] UIntPtr* pdwRefData);
```

This API is not exported **by name** in comctl32.

```
dumpbin /exports C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22494.1000_none_73d55deb5fb89285\COMCTL32.dll

...
411      0001D0E0 [NONAME]
...
```

See also: microsoft/windows-rs#1294

**Comment by sotteson1** [comment]
The docs for GetProcAddress say it is meant to work for functions exported by ordinal. It says to import by ordinal only if you have control over how the ordinals are assigned. In my testing, calling GetProcAddress for GetWindowSubclass only works if the manifest for your app indicates the app supports Common Controls 6.0. Otherwise, when you load the library, the older one loads and GetProcAddress will return null.

**Comment by riverar** [comment]
@sotteson1 Try this out:

```cpp
#include <commctrl.h>
int main()
{
    #pragma comment(lib, "onecoreuap.lib")
    auto _ = GetWindowSubclass(nullptr, nullptr, 0, nullptr);
}
```

Observe the app compiles and runs. I believe `onecoreuap.lib` exports this particular function _by ordinal_ not _by name_ (recall there are separate structures for this in the lib). Sadly this is not something dumpbin appears to expose in its console output.

**Comment by sotteson1** [comment]
That function is not meant to be used unless the app manifest specifies comctl 6.0:

https://docs.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-getwindowsubclass

"To use GetWindowSubclass, specify Comctl32.dll version 6 in the manifest. For more information on manifests, see Enabling Visual Styles."

If the app has the manifest, then LoadLibrary works with that name. I just looked at the source in Window between 5 and 6. Version 5 def file:

        GetWindowSubclass               @411    NONAME PRIVATE

Version 6 def file:

        GetWindowSubclass               @411

They are purposely removing the name on version 5 and marking it as private. I could do a one off for this function and use the ordinal instead of the name, but since the docs say it's only supposed to work with when version 6 is being used, it seems like we're already doing the right thing.

**Comment by riverar** [comment]
@sotteson1 Thanks for checking that so quickly.

This is going to be a tough conversation with customers given comctl32.lib/onecoreuap.lib let devs call this API (incorrectly) in comctl32 5.0. And now the "fix" is to create/carry a fusion manifest.

I believe there are other affected APIs in comctl so a one-off probably won't be productive.

Feel free to close for now, no action needed.
