### ISSUE TITLE
Missing Gdiplus flat API

### ISSUE THREAD

**Issue by Lexikos** [microsoft/win32metadata#742]
The metadata appears to be missing the [GDI+ flat API](https://docs.microsoft.com/en-us/windows/win32/gdiplus/-gdiplus-flatapi-flat); e.g. `GdiplusStartup`, `GdipCreateBitmapFromFile`, `GpBitmap`, etc.

**Comment by mikebattista** [comment]
I believe these were excluded since they are C++ classes which we don't support in the metadata.

https://github.com/microsoft/win32metadata/blob/6b2be35aca1c1b8945dcbfa6300734a94eb0bbeb/scripts/HeaderFileCoverageExceptions.csv#L168-L198

Assigning to @sotteson1 to confirm.

**Comment by kennykerr** [comment]
GDI+ is mostly a C++ API but is backed by a "flat" C API.

**Comment by mikebattista** [comment]
So is the ask just for gdiplusflat.h and not the other headers listed above?

**Comment by kennykerr** [comment]
It's not my issue, but that header is the only part of GDI+ that makes any sense to include.

**Comment by mikebattista** [comment]
It looks like the signatures in that header refer to C++ classes in GdiplusGpStubs.h which might still be problematic.

@sotteson1 will need to take a look.

**Comment by sotteson1** [comment]
Unfortunately, I don't see how we can add support for this. Even in the flat API, all the types are classes with implementation, which we can't express in metadata.

**Comment by wqweto** [comment]
I was wondering if it's possible for all class pointers in GDI+ flat API be converted to opaque handles?

I.e. this
```
GpStatus WINGDIPAPI
GdipCreatePath(GpFillMode brushMode, GpPath **path);
```
to be treated like
```
GpStatus WINGDIPAPI
GdipCreatePath(GpFillMode brushMode, HANDLE *path);
```
where `HANDLE` is some typedef of `void *` or other type.

This is what other languages (other than C++) do in order to declare GDI+ flat API because such C++ pointers most often cannot be used to call any class method when API is used outside of C++ (in these other languages).
