### ISSUE TITLE
Flag structs in `Win32::UI::Shell::PropertiesSystem` are missing bitwise traits

### ISSUE THREAD

**Issue by ok-nick** [microsoft/win32metadata#746]
Each struct that holds an integer for flags in the `Win32::UI::Shell::PropertiesSystem` module are missing bitwise trait implementations. For example, the `GETPROPERTYSTOREFLAGS` and `PROPVAR_COMPARE_FLAGS` structs.

**Comment by mikebattista** [comment]
I left PROPDESC_TYPE_FLAGS commented out since a couple of its trailing members were getting scraped as unchecked ints and then failing to convert to uint.

@sotteson1 could you take a look at that one? Repro is uncomment the below and rebuild.

https://github.com/microsoft/win32metadata/blob/50a2585cd2b03d8d75bafd3e1450d27f6a6dc7e3/generation/WinSDK/emitter.settings.rsp#L76
