### ISSUE TITLE
`LSTATUS` 

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#760]
The various registry functions like `RegOpenKeyExW` and `SHRegGetPathA` return `LSTATUS` but all the actual error codes mentioned in the docs appear to come from the `WIN32_ERROR` enum, makiing it hard to use theses functions as you have to cast between `LSTATUS` and `WIN32_ERROR`. 

Should any mention of `LSTATUS` perhaps just be replaced with `WIN32_ERROR`?

Customer reported issue: https://github.com/microsoft/windows-rs/issues/1367

**Comment by AArnott** [comment]
I wonder if the `AlsoUsableForAttribute` applied to `LSTATUS` would be a hint to projections that `LSTATUS` should be implicitly castable to (its superset) `WIN32_ERROR`. If that solved the problem, it may be preferable to simply removing `LSTATUS` from the metadata because it helps document the subset of errors these functions may return, and it matches the headers/docs more closely.

**Comment by mikebattista** [comment]
A crude header search shows that LSTATUS is only returned by these registry APIs as far as I can tell. I've already remapped the return values to WIN32_ERROR. Should we just remove the LSTATUS type?

**Comment by kennykerr** [comment]
Yes, only the registry APIs mention LSTATUS and the docs for those same APIs only refer to WIN32_ERROR codes. I'm in favor of removing LSTATUS and keeping things simple.
