### ISSUE TITLE
Metadata should annotate methods which return unowned handles

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/win32metadata#792]
## Actual behavior

The generated code for GetClipboardData exposes GetClipboardData_SafeHandle using a SafeHandle that owns the handle even though the handle returned by GetClipboardData is always owned by the clipboard.

## Expected behavior

No overload using a safehandle with ownsHandle set to true should be generated.

## Repro steps

1. `NativeMethods.txt` content:
```
GetClipboardData
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: 0.1.632-beta
- Win32Metadata version (if explicitly set by project):
- Target Framework: net6.0
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by mikebattista** [comment]
Is the proposal just a new attribute on the impacted functions?

**Comment by AArnott** [comment]
Either an attribute on the return value or output parameter that produces the unowned handle, or use a new typedef struct that lacks the `RAIIFree` attribute. I'm a bit concerned that a new type would hurt interop with other APIs so I'm leaning toward the attribute approach.

**Comment by kennykerr** [comment]
Yep, I think an attribute would be less disruptive.

**Comment by mikebattista** [comment]
What name should we use for this attribute? `[ReturnsUnownedHandle]`?

Also typically we would apply such an attribute to the function itself rather than on the return value. Any objections to that?

**Comment by riverar** [comment]
I don't understand how we can support this, without someone carefully looking (and monitoring?) at every single implementation across the N builds of Windows that metadata is modeling.

**Comment by riverar** [comment]
I suppose we can key off the documented handle behavior for this instance, but without broad applicability I wonder if there's any value in adding this attribute.

**Comment by mikebattista** [comment]
How would you handle this case?

**Comment by riverar** [comment]
My hot take is that CsWin32 needs to scrap the use of SafeHandle in its codegen and let the developer opt-in by wrapping the handles themselves. But am open to other views!

**Comment by AArnott** [comment]
I think `[ReturnsUnownedHandle]` is a fine name. But as some handles are on out parameters, and in fact some function (e.g. [`CreatePipe`](https://learn.microsoft.com/en-us/windows/win32/api/namedpipeapi/nf-namedpipeapi-createpipe)) have *multiple* handle output parameters, I believe we should apply the attribute to the return value or parameters that it describes rather than the function, which may leave the question ambiguous.

Most functions return owned handles, and a bug-driven application of the new attribute in the rare cases where it is needed seems like a far better outcome for C# customers than throwing in the towel and making all users repeatedly look up the handle owning semantics themselves and hoping they interpret the docs and implement it correctly. Most C# users simply aren't familiar with interop enough to get this right without relying on SafeHandles.

**Comment by mikebattista** [comment]
Sure we can try that.

**Comment by mikebattista** [comment]
Does CreatePipe need the attribute here or just GetClipboardData?
