### ISSUE TITLE
`Win32::System::SqlLite` is mis-named

### ISSUE THREAD

**Issue by MaulingMonkey** [microsoft/win32metadata#824]
* `SqlLite`, as per the module and feature name, has two `L`s
* The actual library is named `SQLite` - one `L`.
* The APIs are all prefixed with `sqlite3_` and `SQLITE_` - one `L`.
* The headers and dlls are named `winsqlite` - one `L`.

**Comment by kennykerr** [comment]
Here's the official homepage for SQLite where you can see the actual naming: https://sqlite.org/

By the way, I don't think the Windows SDK should include SQLite. It's not a Windows API at all.

**Comment by riverar** [comment]
@kennykerr Agree. I can't even find official docs on that API surface, which worries me a bit. It's not clear what's different between winsqlite3 and official sqlite3, the servicing strategy, etc. (The ABI between the two is also different.)

@mikebattista Shall we just cut all these APIs? Thoughts?

**Comment by mikebattista** [comment]
I'm fine removing these.

**Comment by riverar** [comment]
@mikebattista Any insight into why the SDK ships them? That rationale might support keeping them in metadata? Just thinking out loud.

**Comment by kennykerr** [comment]
Windows ships a compiled version of SQLite in `System32/winsqlite3.dll` that certain OS projects depend on. If you want to use this version to reduce your overall binary size, you can link against this version instead of compiling it directly into your own project. 

I don't recommend that for non-OS projects, but that's where it comes from. @jonwis may have some guidance here.
