### ISSUE TITLE
Invalid MulticastDelegate

### ISSUE THREAD

**Issue by taufikrh** [microsoft/win32metadata#846]
The following TypeDef is emitted as `MulticastDelegate`, actually should be `Pointer of MulticastDelegate`. The Invoke parameters on each function is empty. Are the metadata correct ?

`Windows.Win32.Networking.WinHttp.LPWINHTTP_STATUS_CALLBACK`
`Windows.Win32.System.AddressBook.PFNIDLE`
`Windows.Win32.Storage.IscsiDisc.PDUMP_DEVICE_POWERON_ROUTINE`

Thanks

**Comment by sotteson1** [comment]
LPWINHTTP_STATUS_CALLBACK looks to me like a bug in the header. Nothing uses it anywhere in the SDK, and I'm going to remove it from the metadata.

PFNIDLE and PDUMP_DEVICE_POWERON_ROUTINE need to be fixed in functionPointerFixups.json. They aren't pointers to delegates, because they point to function prototypes and not function pointers. So, they will just be delegates but with the right parameters.

Thanks for finding these issues.
