### ISSUE TITLE
How to compute permalink to docs?

### ISSUE THREAD

**Issue by kennykerr** [microsoft/win32metadata#865]
Is there a way we can derive a link to the MSDN docs for a given type or function in the metadata programmatically? 

For example, how do I map from:
`Windows.Win32.System.Threading.CreateEventA` 
To this:
https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createeventa

Or from:
`Windows.Win32.Graphics.Direct2D.Common.D2D1_COLOR_F`
To this:
https://docs.microsoft.com/en-us/windows/win32/direct2d/d2d1-color-f

Is there such a mapping? 

Maybe @stevewhims knows...

**Comment by stevewhims** [comment]
So for the CreateEventA example, the `https://docs.microsoft.com/windows/win32/api/` part is going to be the same for all Win32/COM APIs. I’ve removed the “en-us” bit, so the customer’s browser will select the right LCID.

After that common root, next comes the name of the header containing the API. So it’s the synchapi.h header in this case. So that’s predictable, too.

Then for the .md file name, again it’s pretty predictable, and in 3 parts. The first part is “ne” for an enum, “nf” for a function, and so on. The second part is the header name again. And the third part is either the to-lower’d API name, or it’s <iface><method> (for example, nf-unknwn-iunknown-addref).

And then for overloads, you can get things like nf-unknwn-iunknown-queryinterface(q) or nf-unknwn-iunknown-queryinterface(refiid_void). I don’t know what the grammar is for those.

For the D2D1_COLOR_F example, that is actually a fake (or hand-crafted) API ref topic published out of a conceptual repo. If the content build system doesn’t recognize an API in the header, then we have to hand-craft topics in that way. So the urls to those would be pretty unpredictable. When I do it, I use a naming convention that’s as close as possible to what the build system would gen. But since it’s an off-the-beaten-track kind of thing, there’s no oversight, and hence very likely no consistency between writers.

However, this is an example of where Direct2D structures (etc) should live: [D2D_MATRIX_3X2_F](https://docs.microsoft.com/windows/win32/api/dcommon/ns-dcommon-d2d_matrix_3x2_f). And again that’s a predictable url.

I've sent internal mail to see if we can get more info.

-Steve

**Comment by kennykerr** [comment]
Thanks Steve, that sounds interesting. It's not something I could use as I need something I can bake into a compiler, but it sounds like something @sotteson1 may be able to use to add the links to metadata. 

Reasons I wouldn't be able to include it are (1) by the time I parse the metadata the header names are long gone and (2) I need something that's completely predictable, so lossy unpredictable URLs won't do.

**Comment by mikebattista** [comment]
I found a way to do this by parsing the .md files directly in the MicrosoftDocs/sdk-api repo. See https://github.com/microsoft/win32metadata/commit/62a25c42b54cae5f8a599f28b03dbd53948b8cf7#diff-fc71c69586d7b98818375db3fe6eb06725caf1f1fc0c44a8d0d310038286d10b. It outputs a remap file that adds `[Documentation("<URI>")]` to APIs.

@stevewhims could you take a look and let me know how we might include the hand-crafted outliers you mentioned following a similar pattern?

**Comment by stevewhims** [comment]
Hi, Mike. I suspect it'll be tricky, if it's possible at all. I've pinged you an email with more info. :)

-Steve
