### ISSUE TITLE
GetMonitorInfo missing override method

### ISSUE THREAD

**Issue by l619534951** [microsoft/win32metadata#981]
### method
User32.dll GetMonitorInfo 
### msdn docs
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmonitorinfoa

### what happen ?
CsWin32 only generated one method of User32.dll GetMonitorInfo.  
- [x] GetMonitorInfo(IntPtr hMonitor, [In, Out] MONITORINFO lpmi)  
- [ ] GetMonitorInfo(IntPtr hMonitor, [In, Out] MONITORINFOEX lpmi)  

### what should happen ?
CsWin32 should generated two method of User32.dll GetMonitorInfo just like precompiled NuGet packages with Win32 P/Invokes.  
- [x] GetMonitorInfo(IntPtr hMonitor, [In, Out] MONITORINFO lpmi)  
- [x] GetMonitorInfo(IntPtr hMonitor, [In, Out] MONITORINFOEX lpmi)  

### precompiled NuGet packages with Win32 P/Invokes docs
http://pinvoke.net/search.aspx?search=GetMonitorInfo&namespace=[All]

### the same issue, but had not been solved yet.
#453

**Comment by AArnott** [comment]
As a workaround in CsWin32, you can use the `GetMonitorInfo` method that takes `MONITORINFO*` and pass it a `MONITORINFOEX*` instead, casting the pointer.

**Comment by riverar** [comment]
@AArnott Think this belongs in your repo., or are you expecting something from the metadata side?

**Comment by l619534951** [comment]
> As a workaround in CsWin32, you can use the `GetMonitorInfo` method that takes `MONITORINFO*` and pass it a `MONITORINFOEX*` instead, casting the pointer.

I found that both methods return false on my computer, so I'm sorry I can't test whether the solution you said can work normally.  
#### Both of the following functions return false on my computer
> GetMonitorInfo(IntPtr hMonitor, [In, Out] MONITORINFO lpmi)
> GetMonitorInfo(IntPtr hMonitor, [In, Out] MONITORINFOEX lpmi)

**Comment by riverar** [comment]
@l619534951 Are you seeing the `cbSize` member to the size of the structure? That's required for this API to work correctly.

**Comment by l619534951** [comment]
> @l619534951 Are you seeing the `cbSize` member to the size of the structure? That's required for this API to work correctly.

Thanks you, it works. I'm just learned Windows development for a few days. Love you so much!!!

**Comment by AArnott** [comment]
> are you expecting something from the metadata side?

I bit late to answer the question, but there's nothing more CsWin32 can do without metadata giving us hints.

 I'd love to see metadata include hints so that CsWin32 can make this better. I'm not sure if overloads are the best way to go, because some languages (e.g. javascript, rust?) don't support method overloading, and that will make it difficult for them to know what to generate. But maybe an attribute on the parameter indicating "also this type is acceptable" so that the projection can do whatever is most natural in the language. In C# we would produce overloads.



One question is how far we might go. For GetMonitorInfo there are just two options. But other methods (e.g. DeviceIoControl) take an int param that tells the receiver which of many types another parameter actually points to. Do we want to go so far as to generate 15+ overloads, possibly with known associations with another parameter value linked to the type of another parameter? I'm thinking not.
